import {createRecord} from '../core/record.js';
import {withIdempotency,createOperationId} from '../core/idempotency.js';
import {calculateWorkSession,expectedTomorrowKm} from '../domain/work.js';
import {rollingFuelCostPerKm,projectedFuelCostForKm} from '../domain/fuel.js';
import {businessExpenses,fixedExpensePerBusinessKm} from '../domain/expenses.js';
import {provisionMaintenance,reconcileInvoice,maintenanceAlerts} from '../domain/maintenance.js';
import {businessRevenue} from '../domain/revenue.js';
import {amortize,applyPrepayment} from '../domain/loans.js';
import {profitability,tomorrowTarget} from '../domain/dashboard.js';
import {evaluateAlerts} from '../domain/alerts.js';
import {performanceReadModel} from './read-models.js';
import {adminReadModel} from './admin-read-model.js';
import {buildTimelineReadModel} from './timeline-read-model.js';
import {createDependencyGraph} from '../core/dependency-graph.js';
import {createOperationalTelemetry} from '../services/operational-telemetry.js';
import {createWorkApplication} from './work-lifecycle.js';
import {createHistoricalCorrections} from './historical-corrections.js';
import {createAdministratorApplication} from './administrator.js';

export function createKfeApplication(repository){
 const graph=createDependencyGraph();
 for(const n of ['work.km','work.tomorrowKm','fuel.costPerKm','fuel.tomorrowCost','maintenance.provision','maintenance.reconciliation','expenses.business','expenses.fixedPerKm','revenue.business','loan.amortization','loan.cashCost','dashboard.profitability','dashboard.tomorrowTarget'])graph.addNode(n,{owner:n.split('.')[0]});
 graph.addDependency('work.km','work.tomorrowKm');graph.addDependency('fuel.costPerKm','fuel.tomorrowCost');graph.addDependency('work.tomorrowKm','dashboard.tomorrowTarget');graph.addDependency('fuel.tomorrowCost','dashboard.tomorrowTarget');graph.addDependency('expenses.fixedPerKm','dashboard.tomorrowTarget');graph.addDependency('maintenance.provision','dashboard.tomorrowTarget');graph.addDependency('loan.amortization','loan.cashCost');graph.addDependency('loan.cashCost','dashboard.profitability');graph.addDependency('revenue.business','dashboard.profitability');graph.addDependency('fuel.costPerKm','dashboard.profitability');graph.addDependency('maintenance.reconciliation','dashboard.profitability');
 const telemetry=createOperationalTelemetry(repository);const work=createWorkApplication({repository,telemetry});const historicalCorrections=createHistoricalCorrections(repository);const administrator=createAdministratorApplication({repository});
 async function create(store,data,meta={}){const record=createRecord(data,meta);repository.assertRecord(record);await repository.atomic([store],stores=>{stores[store].put(record);return record;});return record;}
 async function startWork(data,operationId=createOperationId()){return withIdempotency(repository,operationId,async()=>create('work_sessions',{...data,status:'OPEN'},{}));}
 async function getWork(id){return repository.entity('work_sessions').get(id);} async function listWork(){return repository.entity('work_sessions').list();}
 async function completeWork(id,data,operationId=createOperationId()){return withIdempotency(repository,operationId,async()=>{const existing=await repository.entity('work_sessions').get(id);if(!existing)throw new Error('Work session not found');const updated=repository.updateRecord(existing,{...data,status:'COMPLETED'});repository.assertRecord(updated);await repository.atomic(['work_sessions','revenue_records'],stores=>{stores.work_sessions.put(updated);if(data.revenue_paise!=null)stores.revenue_records.put(createRecord({work_session_id:id,amount_paise:data.revenue_paise,scope:'BUSINESS'},{id:data.revenue_id||createOperationId(),user_id:existing.user_id}));return true;});return updated;});}
 async function recordHistoricalDay(data,operationId=createOperationId()){return withIdempotency(repository,operationId,async()=>{const date=String(data.date||'');const start=Number(data.start_odometer);const end=Number(data.end_odometer);const revenue=Number(data.revenue_paise);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(start)||start<0||!Number.isFinite(end)||end<start||!Number.isInteger(revenue)||revenue<0)throw new Error('Invalid historical day');const id=createOperationId();const session=createRecord({business_date:date,start_at:`${date}T00:00:00.000Z`,end_at:`${date}T23:59:59.999Z`,start_odometer:start,end_odometer:end,status:'COMPLETED',scope:'BUSINESS',entry_source:'HISTORICAL',is_historical:true},{id});repository.assertRecord(session);const revenueRecord=createRecord({work_session_id:id,amount_paise:revenue,scope:'BUSINESS',business_date:date,recorded_at:`${date}T12:00:00.000Z`,entry_source:'HISTORICAL',is_historical:true},{user_id:session.user_id});await repository.atomic(['work_sessions','revenue_records'],stores=>{stores.work_sessions.put(session);stores.revenue_records.put(revenueRecord);return true;});return session;});}
 async function listFuel(){return repository.entity('fuel_records').list();}
 async function recordFuel(data,operationId=createOperationId()){return withIdempotency(repository,operationId,async()=>{const odometer=Number(data.odometer);if(!Number.isInteger(odometer)||odometer<0)throw new RangeError('Fuel odometer must be a whole number');const latest=await work.latestOdometer();if(latest&&odometer<Number(latest.odometer))throw new RangeError('Fuel odometer cannot be below the authoritative odometer');const price=Number(data.price_per_kg),amount=Number(data.amount_paise);if(!Number.isFinite(price)||price<=0)throw new RangeError('Fuel price must be positive');if(!Number.isInteger(amount)||amount<=0)throw new RangeError('Fuel amount must be positive');return repository.entity('fuel_records').create({...data,odometer,quantity_kg:amount/100/price,fuel_type:'CNG'},{});});}
 async function recordHistoricalFuel(data,operationId=createOperationId()){return withIdempotency(repository,operationId,async()=>{const date=String(data.date||'');const odometer=Number(data.odometer);const amount=Number(data.amount_paise);const price=Number(data.price_per_kg);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(odometer)||odometer<0||!Number.isInteger(amount)||amount<=0||!Number.isFinite(price)||price<=0)throw new Error('Invalid historical fuel entry');return create('fuel_records',{date,recorded_at:`${date}T12:00:00.000Z`,odometer,amount_paise:amount,price_per_kg:price,quantity_kg:amount/100/price,fuel_type:'CNG',scope:'BUSINESS',entry_source:'HISTORICAL',is_historical:true},{});});}
 async function updateFuel(id,changes,operationId=createOperationId()){return withIdempotency(repository,operationId,async()=>{const existing=await repository.entity('fuel_records').get(id);if(!existing)throw new Error('Fuel record not found');const amount=Number(changes.amount_paise),price=Number(changes.price_per_kg);if(!Number.isInteger(amount)||amount<=0||!Number.isFinite(price)||price<=0)throw new RangeError('Fuel amount and price must be positive');const latest=await work.latestOdometer();const odometer=Number(changes.odometer);if(!Number.isInteger(odometer)||odometer<0||(latest&&odometer<Number(latest.odometer)))throw new RangeError('Fuel odometer cannot be below the authoritative odometer');return repository.entity('fuel_records').update(existing,{...changes,odometer,quantity_kg:amount/100/price,fuel_type:'CNG'});});}
 async function undoFuel(id){const existing=await repository.entity('fuel_records').get(id);if(!existing)return null;return repository.entity('fuel_records').softDelete(existing);}
 async function listTrips(){return repository.entity('rides').list();} async function recordTrip(data,operationId=createOperationId()){return withIdempotency(repository,operationId,async()=>create('rides',data,{}));} async function updateTrip(id,changes,operationId=createOperationId()){return withIdempotency(repository,operationId,async()=>{const existing=await repository.entity('rides').get(id);if(!existing)throw new Error('Trip not found');return repository.entity('rides').update(existing,changes);});} async function undoTrip(id){const existing=await repository.entity('rides').get(id);if(!existing)return null;return repository.entity('rides').softDelete(existing);}
 async function recordRevenue(data,operationId=createOperationId()){return withIdempotency(repository,operationId,async()=>create('revenue_records',data,{}));}
 async function recordExpense(data,operationId=createOperationId()){return withIdempotency(repository,operationId,async()=>{const amount=Number(data.amount);if(!Number.isFinite(amount)||amount<=0)throw new RangeError('Expense amount must be positive');return create('expense_records',{category:data.category,date:data.date,amount_paise:Math.round(amount*100),description:data.description||'',reference:data.reference||'',scope:'BUSINESS'},{});});}
 async function recordMaintenance(data,operationId=createOperationId()){return withIdempotency(repository,operationId,async()=>{const amount=Number(data.amount),odometer=Number(data.odometer);if(!Number.isFinite(amount)||amount<=0)throw new RangeError('Maintenance amount must be positive');if(!Number.isInteger(odometer)||odometer<0)throw new RangeError('Maintenance odometer must be a whole number');return create('maintenance_records',{maintenance_id:data.maintenanceId||null,date:data.date,vehicle:data.vehicle,odometer,category:data.category,description:data.description,amount_paise:Math.round(amount*100),reference:data.reference||null,work_session_id:data.workSessionId||null},{});});}
 async function recordCompliance(data,operationId=createOperationId()){return withIdempotency(repository,operationId,async()=>{const cost=Number(data.cost);if(!Number.isFinite(cost)||cost<=0)throw new RangeError('Renewal cost must be positive');return create('renewals_compliance',{renewal_type:data.type,cost_paise:Math.round(cost*100),validity_start:data.start,validity_end:data.end},{});});}
 async function recordVehicleLifecycle(data,operationId=createOperationId()){return withIdempotency(repository,operationId,async()=>{const rows=(await repository.entity('vehicles').list()).filter(row=>!row.is_deleted);const existing=rows[0]||null;const changes={acquisition_date:data.acquisitionDate||null,retirement_date:data.retirementDate||null};if(existing)return repository.entity('vehicles').update(existing,changes);return create('vehicles',changes,{});});}
 async function getPerformance(asOf=new Date().toISOString()){return performanceReadModel({repository,asOf});}
 async function getAdminState(asOf=new Date().toISOString()){return adminReadModel({repository,asOf});}
 async function getTimeline(horizon='Day',asOf=new Date().toISOString()){return buildTimelineReadModel({repository,horizon,asOf});}
 async function resetAllData(){if(typeof indexedDB==='undefined')throw new Error('IndexedDB unavailable');await new Promise((resolve,reject)=>{const request=indexedDB.deleteDatabase('kfe');request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error||new Error('Data reset failed'));request.onblocked=()=>reject(new Error('Data reset blocked by an open database connection'));});}
 return Object.freeze({graph,administrator,work,telemetry,historicalCorrections,saveHistoricalCorrection:historicalCorrections.save,startWork,getWork,listWork,completeWork,recordHistoricalDay,listFuel,recordFuel,recordHistoricalFuel,updateFuel,undoFuel,listTrips,recordTrip,updateTrip,undoTrip,recordRevenue,recordExpense,recordMaintenance,recordCompliance,recordVehicleLifecycle,getPerformance,getAdminState,getTimeline,resetAllData,calculateWorkSession,expectedTomorrowKm,rollingFuelCostPerKm,projectedFuelCostForKm,businessExpenses,fixedExpensePerBusinessKm,provisionMaintenance,reconcileInvoice,maintenanceAlerts,businessRevenue,amortize,applyPrepayment,profitability,tomorrowTarget,evaluateAlerts,getWorkScreenState:work.state,startDay:work.startDay,startShift:work.startShift,startBusinessTrip:work.startBusinessTrip,startPersonalTrip:work.startPersonalTrip,endBusinessTrip:work.endBusinessTrip,endPersonalTrip:work.endPersonalTrip,endShift:work.endShift,endDay:work.endDay,undoWorkAction:work.undo,workSummary:work.summary,latestWorkOdometer:work.latestOdometer});
}
