import {DATA} from '../domain/shared.js';
export const PRESENTATION_READ_MODEL_VERSION=1;
const CONFIDENCE_STATES=new Set(Object.values(DATA));
function stateOf(value){const state=value?.dataConfidenceState;if(CONFIDENCE_STATES.has(state))return state;return value==null?DATA.UNKNOWN:DATA.ACTUAL;}
export function confidenceState(values=[]){const states=values.map(stateOf);if(states.includes(DATA.INSUFFICIENT_DATA))return DATA.INSUFFICIENT_DATA;if(states.includes(DATA.UNKNOWN))return DATA.UNKNOWN;if(states.includes(DATA.PROVISION))return DATA.PROVISION;if(states.includes(DATA.PROJECTED))return DATA.PROJECTED;if(states.includes(DATA.BASELINE))return DATA.BASELINE;return DATA.ACTUAL;}
export function dashboardReadModel({profitabilityResult,tomorrowTargetResult,alerts=[]}={}){return Object.freeze({version:PRESENTATION_READ_MODEL_VERSION,dataConfidenceState:confidenceState([profitabilityResult,tomorrowTargetResult]),profitability:profitabilityResult??null,tomorrowTarget:tomorrowTargetResult??null,alerts:Array.isArray(alerts)?Object.freeze([...alerts]):Object.freeze([])});}
export function workSessionReadModel(session){if(!session)return Object.freeze({dataConfidenceState:DATA.UNKNOWN,session:null});return Object.freeze({dataConfidenceState:stateOf(session),session:Object.freeze({...session})});}
export function statusReadModel({repository,asOf=new Date().toISOString()}={}){return Promise.all([repository.entity('revenue_records').list(),repository.entity('expense_records').list(),repository.entity('fuel_records').list(),repository.entity('work_sessions').list()]).then(([revenue,expenses,fuel,work])=>Object.freeze({version:PRESENTATION_READ_MODEL_VERSION,asOf,dataConfidenceState:confidenceState([...revenue,...expenses,...fuel,...work]),revenuePaise:revenue.reduce((s,r)=>s+Number(r.amount_paise||0),0),expensesPaise:expenses.reduce((s,r)=>s+Number(r.amount_paise||0),0),fuelPaise:fuel.reduce((s,r)=>s+Number(r.amount_paise||0),0),businessKm:work.reduce((s,r)=>s+Number(r.business_km||r.km||0),0),tomorrowKm:null,fuelCostPerKm:null,tomorrowTarget:null}));}
const TIMELINE_SOURCES=[['work_sessions','WORK_SESSION'],['fuel_records','FUEL'],['expense_records','EXPENSE'],['revenue_records','REVENUE'],['maintenance_records','MAINTENANCE'],['renewals_compliance','RENEWAL'],['loan_payments','LOAN_PAYMENT']];
function timelineEvent(record,type){const occurredAt=record.occurredAt||record.date||record.started_at||record.created_at||record.createdAt||record.timestamp;return {id:record.id||`${type}:${occurredAt||'unknown'}`,type,occurredAt:occurredAt||null,description:record.description||record.notes||record.category||null,amount:record.amount_paise!=null?Number(record.amount_paise)/100:record.amount!=null?Number(record.amount):null,odometer:record.odometer!=null?Number(record.odometer):null,locationName:record.locationName||record.location_name||null,dataConfidenceState:stateOf(record)};}
export async function timelineReadModel({repository}={}){const groups=await Promise.all(TIMELINE_SOURCES.map(async([store,type])=>{try{return (await repository.entity(store).list()).map(record=>timelineEvent(record,type));}catch{return []}}));const events=groups.flat().sort((a,b)=>String(b.occurredAt||'').localeCompare(String(a.occurredAt||'')));return Object.freeze({version:PRESENTATION_READ_MODEL_VERSION,dataConfidenceState:confidenceState(events),events:Object.freeze(events.map(event=>Object.freeze(event)))});}
export function presentationError(error){return Object.freeze({dataConfidenceState:DATA.UNKNOWN,error:String(error?.message||error||'Unknown error')});}
