<script setup>
import { computed, onMounted, ref } from 'vue'
import UniversalAdminForm from '../components/admin/UniversalAdminForm.vue'
import { ADMIN_FORM_DEFINITIONS } from '../application/admin/adminFormDefinitions.js'
import { AdminService } from '../application/admin/adminService.js'

const activeSection=ref(null), activeFormKey=ref(null), editingId=ref(null), formValues=ref({}), records=ref({}), errorMessage=ref(''), busy=ref(false)
const meta={operations:{icon:'🛠️',title:'Operations',description:'Authoritative operational source records.'},finance:{icon:'💰',title:'Finance',description:'Authoritative finance source records.'},targetBreakEven:{icon:'🎯',title:'Target & Break-even',description:'Targets and controlled break-even inputs.'},settings:{icon:'⚙️',title:'Settings',description:'Backup, appearance and controlled testing tools.'}}
const sections=computed(()=>Object.entries(meta).map(([key,m])=>({key,...m,forms:Object.values(ADMIN_FORM_DEFINITIONS).filter(d=>d.category===key)})))
const definition=computed(()=>activeFormKey.value?ADMIN_FORM_DEFINITIONS[activeFormKey.value]:null)
const optionSources={vehicleId:'vehicle',driverId:'driver',loanId:'loan'}
const resolvedDefinition=computed(()=>definition.value?{...definition.value,fields:definition.value.fields.map(f=>optionSources[f.key]?{...f,options:(records.value[optionSources[f.key]]||[]).map(r=>r.id)}:f)}:null)
const activeRecords=computed(()=>records.value[activeFormKey.value]||[])
async function refresh(k){records.value[k]=await AdminService.list(k)}
async function refreshAll(){for(const k of Object.keys(ADMIN_FORM_DEFINITIONS))await refresh(k)}
function openForm(k,r=null){activeFormKey.value=k;editingId.value=r?.id||null;formValues.value=r?{...r.values}:{};errorMessage.value=''}
function closeForm(){activeFormKey.value=null;editingId.value=null;formValues.value={}}
async function save(v){busy.value=true;errorMessage.value='';try{await AdminService.save(activeFormKey.value,v,editingId.value);await refresh(activeFormKey.value);closeForm()}catch(e){errorMessage.value=e.validation?Object.values(e.validation).join(' '):e.message}finally{busy.value=false}}
async function remove(r){if(!window.confirm(`Delete this ${definition.value.title} record?`))return;busy.value=true;try{await AdminService.remove(activeFormKey.value,r.id);await refresh(activeFormKey.value)}catch(e){errorMessage.value=e.message}finally{busy.value=false}}
onMounted(()=>refreshAll().catch(e=>errorMessage.value=e.message))
</script>
<template>
<section class="admin-page"><header class="admin-header"><small>ADMIN</small><h1>Control &amp; Records</h1><p>Source-record management through the application/domain authority.</p></header><div v-if="errorMessage" class="admin-error">{{errorMessage}}</div>
<div class="section-grid"><button v-for="s in sections" :key="s.key" class="section-card" type="button" @click="activeSection=s.key"><span class="section-icon">{{s.icon}}</span><strong>{{s.title}}</strong><span>{{s.description}}</span></button></div>
<section v-if="activeSection&&!activeFormKey" class="detail-panel"><div v-for="s in sections.filter(x=>x.key===activeSection)" :key="s.key"><h2>{{s.title}}</h2><article v-for="d in s.forms" :key="d.key" class="record-group"><div class="group-head"><h3>{{d.title}}</h3><button type="button" @click="openForm(d.key)">Add</button></div><div v-for="r in records[d.key]||[]" :key="r.id" class="record-row"><span>{{r.id}}<small>{{r.updatedAt}}</small></span><span><button type="button" @click="openForm(d.key,r)">Edit</button><button type="button" @click="openForm(d.key,r);remove(r)">Delete</button></span></div><p v-if="!(records[d.key]||[]).length" class="empty">No records yet.</p></article></div></section>
<section v-if="activeFormKey&&resolvedDefinition" class="detail-panel"><h2>{{resolvedDefinition.title}}</h2><UniversalAdminForm :definition="resolvedDefinition" :model-value="formValues" :submit-label="busy?'Saving…':'Save'" @update:model-value="formValues=$event" @submit="save" @cancel="closeForm"/><div v-if="activeRecords.length"><h3>Existing records</h3><div v-for="r in activeRecords" :key="r.id" class="record-row"><span>{{r.id}}</span><span><button type="button" @click="openForm(activeFormKey,r)">Edit</button><button type="button" @click="remove(r)">Delete</button></span></div></div></section>
<section class="derived-panel"><small>ERP CALCULATIONS</small><h2>Derived automatically</h2><p>Derived values remain outside Admin source forms.</p></section></section>
</template>
<style scoped>.admin-page{min-height:100%;padding:20px 16px;background:#f8fafc;color:#0f172a}.admin-header{margin-bottom:18px}.admin-header small,.derived-panel small{font-size:.68rem;font-weight:900;letter-spacing:.12em;color:#64748b}.admin-header h1{margin:3px 0}.admin-header p{color:#64748b;font-size:.82rem}.admin-error{padding:10px;margin-bottom:12px;border:1px solid #fca5a5;border-radius:10px;color:#b42318;background:#fff}.section-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.section-card{min-height:130px;text-align:left;border:1px solid #e2e8f0;border-radius:16px;background:#fff;padding:16px;display:flex;flex-direction:column;gap:9px;cursor:pointer}.section-card span:last-child{color:#64748b;font-size:.75rem}.section-icon{font-size:1.6rem}.detail-panel,.derived-panel{margin-top:16px;border:1px solid #e2e8f0;border-radius:16px;background:#fff;padding:16px}.record-group{border:1px solid #e2e8f0;border-radius:12px;margin-top:12px;overflow:hidden}.group-head,.record-row{display:flex;justify-content:space-between;gap:10px;padding:10px 12px}.group-head{background:#f8fafc}.group-head h3{margin:0}.record-row{border-top:1px solid #f1f5f9;font-size:.75rem}.record-row span:first-child{display:flex;flex-direction:column;gap:3px}.record-row small,.empty{color:#64748b}.record-row button,.group-head button{margin-left:6px;padding:6px 9px;border:1px solid #cbd5e1;border-radius:8px;background:#fff}.empty{padding:12px;margin:0;font-size:.72rem}@media(max-width:640px){.section-card{min-height:115px}.admin-page{padding:14px 12px}}</style>
