import { initializeCanonicalStorage } from '../utils/indexedDB.js'
import { generateUUID } from '../utils/uuid.js'
import { buildMutationRecord } from './mutationRepository.js'

const atomic = async (stores, writer) => {
  const db = await initializeCanonicalStorage()
  return new Promise((resolve, reject) => {
    const tx = db.transaction([...stores, 'pending_mutations'], 'readwrite'); const mutationStore = tx.objectStore('pending_mutations')
    try { writer(tx, mutationStore) } catch (e) { reject(e); return }
    tx.oncomplete=()=>resolve(true); tx.onerror=()=>reject(tx.error||new Error('Lifecycle persistence failed.')); tx.onabort=()=>reject(tx.error||new Error('Lifecycle transaction aborted.'))
  })
}
const saveMutation=(m,entityId,entityType,action,payload,createdAt)=>m.put(buildMutationRecord({entityId,entityType,action,payload,createdAt}))

export const DayShiftTripRepository={
  async createDay(data={}){const now=new Date().toISOString();const record={id:data.id||generateUUID(),dayStartAt:data.dayStartAt||now,dayEndAt:null,status:'ACTIVE',hasCompletedBusinessTrip:false,createdAt:now,updatedAt:now};await atomic(['days'],(_,m)=>{_.objectStore('days').put(record);saveMutation(m,record.id,'DAY','CREATE',record,now)});return record},
  async endDay(id){const db=await initializeCanonicalStorage();return new Promise((resolve,reject)=>{const tx=db.transaction(['days','pending_mutations'],'readwrite'),s=tx.objectStore('days'),m=tx.objectStore('pending_mutations'),req=s.get(id);req.onsuccess=()=>{const r=req.result;if(!r){reject(new Error('Day not found.'));return}const now=new Date().toISOString();r.dayEndAt=now;r.status='COMPLETED';r.updatedAt=now;s.put(r);saveMutation(m,r.id,'DAY','UPDATE',r,now)};req.onerror=()=>reject(req.error);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error||new Error('Day end failed.'));tx.onabort=()=>reject(tx.error||new Error('Day end aborted.'))})},
  async createShift(data){const now=new Date().toISOString();const record={id:data.id||generateUUID(),dayId:data.dayId,startOdometer:Number(data.startOdometer),endOdometer:null,totalDistance:0,revenue:0,shiftStartAt:data.shiftStartAt||now,shiftEndAt:null,status:'ACTIVE',createdAt:now,updatedAt:now};await atomic(['shifts'],(_,m)=>{_.objectStore('shifts').put(record);saveMutation(m,record.id,'SHIFT','CREATE',record,now)});return record},
  async endShift(data){const db=await initializeCanonicalStorage();return new Promise((resolve,reject)=>{const tx=db.transaction(['shifts','pending_mutations'],'readwrite'),s=tx.objectStore('shifts'),m=tx.objectStore('pending_mutations'),req=s.get(data.id);req.onsuccess=()=>{const r=req.result;if(!r){reject(new Error('Active shift not found.'));return}const now=new Date().toISOString();r.endOdometer=Number(data.endOdometer);r.totalDistance=r.endOdometer-r.startOdometer;r.revenue=Number(data.revenue);r.shiftEndAt=now;r.status='COMPLETED';r.updatedAt=now;s.put(r);saveMutation(m,r.id,'SHIFT','UPDATE',r,now)};req.onerror=()=>reject(req.error);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error||new Error('Shift end failed.'));tx.onabort=()=>reject(tx.error||new Error('Shift end aborted.'))})},
  async createTrip(data){const now=new Date().toISOString();const record={id:data.id||generateUUID(),dayId:data.dayId,shiftId:data.shiftId,tripStartAt:data.tripStartAt||now,tripEndAt:null,status:'ACTIVE',tripStartLocation:data.tripStartLocation||null,tripEndLocation:null,uberBusinessKm:null,uberBusinessKmAuthority:'ESTIMATE',uberRevenue:null,uberRevenueAuthority:'ESTIMATE',createdAt:now,updatedAt:now};await atomic(['trips'],(_,m)=>{_.objectStore('trips').put(record);saveMutation(m,record.id,'TRIP','CREATE',record,now)});return record},
  async endTrip(data){const db=await initializeCanonicalStorage();return new Promise((resolve,reject)=>{const tx=db.transaction(['trips','days','pending_mutations'],'readwrite'),t=tx.objectStore('trips'),d=tx.objectStore('days'),m=tx.objectStore('pending_mutations'),req=t.get(data.id);req.onsuccess=()=>{const r=req.result;if(!r){reject(new Error('Active trip not found.'));return}const now=new Date().toISOString();r.tripEndAt=data.tripEndAt||now;r.status='COMPLETED';r.tripEndLocation=data.tripEndLocation||null;r.updatedAt=now;t.put(r);saveMutation(m,r.id,'TRIP','UPDATE',r,now);const dayReq=d.get(r.dayId);dayReq.onsuccess=()=>{const day=dayReq.result;if(day){day.hasCompletedBusinessTrip=true;day.updatedAt=now;d.put(day);saveMutation(m,day.id,'DAY','UPDATE',day,now)}}};req.onerror=()=>reject(req.error);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error||new Error('Trip end failed.'));tx.onabort=()=>reject(tx.error||new Error('Trip end aborted.'))})},
  async getCompletedTrips(dayId){const db=await initializeCanonicalStorage();return new Promise((resolve,reject)=>{const tx=db.transaction(['trips'],'readonly'),req=tx.objectStore('trips').getAll();req.onsuccess=()=>resolve((req.result||[]).filter(x=>x.status==='COMPLETED' && (!dayId || x.dayId===dayId)).sort((a,b)=>new Date(a.tripStartAt)-new Date(b.tripStartAt)));req.onerror=()=>reject(req.error);tx.onerror=()=>reject(tx.error||new Error('Trip query failed.'))})},
  async getCompletedTripsForShift(shiftId){const trips=await this.getCompletedTrips();return trips.filter(x=>x.shiftId===shiftId)},
  async updateTripReconciliation(data){const db=await initializeCanonicalStorage();return new Promise((resolve,reject)=>{const tx=db.transaction(['trips','pending_mutations'],'readwrite'),s=tx.objectStore('trips'),m=tx.objectStore('pending_mutations'),req=s.get(data.id);req.onsuccess=()=>{const r=req.result;if(!r){reject(new Error('Trip not found.'));return}const now=new Date().toISOString();if(data.uberBusinessKm!==undefined){const km=Number(data.uberBusinessKm);if(!Number.isFinite(km)||km<0){reject(new Error('Uber Business KM must be a non-negative number.'));return}r.uberBusinessKm=km;r.uberBusinessKmAuthority='MANUAL_UBER'}if(data.uberRevenue!==undefined){const revenue=Number(data.uberRevenue);if(!Number.isFinite(revenue)||revenue<0){reject(new Error('Uber Revenue must be a non-negative number.'));return}r.uberRevenue=revenue;r.uberRevenueAuthority='MANUAL_UBER'}r.updatedAt=now;s.put(r);saveMutation(m,r.id,'TRIP','UPDATE',r,now)};req.onerror=()=>reject(req.error);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error||new Error('Trip reconciliation failed.'));tx.onabort=()=>reject(tx.error||new Error('Trip reconciliation aborted.'))})},
  async getLastCompletedShift(){const db=await initializeCanonicalStorage();return new Promise((resolve,reject)=>{const tx=db.transaction(['shifts'],'readonly'),req=tx.objectStore('shifts').getAll();req.onsuccess=()=>{const shifts=(req.result||[]).filter(x=>x.status==='COMPLETED'&&Number.isFinite(Number(x.endOdometer))&&Number(x.endOdometer)>=0).sort((a,b)=>new Date(b.shiftEndAt||b.updatedAt||b.createdAt)-new Date(a.shiftEndAt||a.updatedAt||a.createdAt));resolve(shifts[0]||null)};req.onerror=()=>reject(req.error);tx.onerror=()=>reject(tx.error||new Error('Shift query failed.'))})},
  async createInterShiftGap(data){const now=new Date().toISOString();const record={id:data.id||generateUUID(),previousShiftId:data.previousShiftId,currentShiftId:data.currentShiftId,previousShiftEndOdometer:Number(data.previousShiftEndOdometer),currentShiftStartOdometer:Number(data.currentShiftStartOdometer),gapKm:Number(data.gapKm),personalKm:null,deadKm:null,unclassifiedKm:null,status:'OPEN',createdAt:now,updatedAt:now};await atomic(['odoGaps'],(_,m)=>{_.objectStore('odoGaps').put(record);saveMutation(m,record.id,'ODO_GAP','CREATE',record,now)});return record},
  async getOpenInterShiftGap(currentShiftId){const db=await initializeCanonicalStorage();return new Promise((resolve,reject)=>{const tx=db.transaction(['odoGaps'],'readonly'),req=tx.objectStore('odoGaps').getAll();req.onsuccess=()=>resolve((req.result||[]).filter(x=>x.currentShiftId===currentShiftId&&x.status==='OPEN').sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))[0]||null);req.onerror=()=>reject(req.error);tx.onerror=()=>reject(tx.error||new Error('Odometer gap query failed.'))})},
  async allocateInterShiftGap(data){const db=await initializeCanonicalStorage();return new Promise((resolve,reject)=>{const tx=db.transaction(['odoGaps','pending_mutations'],'readwrite'),s=tx.objectStore('odoGaps'),m=tx.objectStore('pending_mutations'),req=s.get(data.id);req.onsuccess=()=>{const r=req.result;if(!r){reject(new Error('Inter-shift odometer gap not found.'));return}const now=new Date().toISOString();r.personalKm=Number(data.personalKm);r.deadKm=Number(data.deadKm);r.unclassifiedKm=Number(data.unclassifiedKm);r.status='ALLOCATED';r.updatedAt=now;s.put(r);saveMutation(m,r.id,'ODO_GAP','UPDATE',r,now)};req.onerror=()=>reject(req.error);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error||new Error('Odometer gap allocation failed.'));tx.onabort=()=>reject(tx.error||new Error('Odometer gap allocation aborted.'))})},
  async getActive(){const db=await initializeCanonicalStorage();return new Promise((resolve,reject)=>{const tx=db.transaction(['days','shifts','trips'],'readonly'),ds=tx.objectStore('days').getAll(),ss=tx.objectStore('shifts').getAll(),ts=tx.objectStore('trips').getAll();let n=0,out={day:null,shift:null,trip:null};const done=()=>{if(++n<3)return;out.day=(ds.result||[]).find(x=>x.status==='ACTIVE')||null;out.shift=(ss.result||[]).find(x=>x.status==='ACTIVE')||null;out.trip=(ts.result||[]).find(x=>x.status==='ACTIVE')||null;resolve(out)};ds.onsuccess=done;ss.onsuccess=done;ts.onsuccess=done;ds.onerror=()=>reject(ds.error);ss.onerror=()=>reject(ss.error);ts.onerror=()=>reject(ts.error)})}
}
