<script setup>
import { computed, onMounted, ref, watch } from 'vue'
const props=defineProps({application:{type:Object,required:true},online:{type:Boolean,default:true}})
const emit=defineEmits(['open','back'])
const section=ref('home'),week=ref(null),model=ref(null),loanModel=ref(null),loading=ref(true),error=ref(''),month=ref(new Date().toISOString().slice(0,7))
const fixedExpenseOpen=ref(false),fixedExpenseEditing=ref(null),fixedExpenseBusy=ref(false),fixedExpenseError=ref('')
const fixedExpenseForm=ref({name:'',category:'',amount:'',effective_from:new Date().toISOString().slice(0,10),status:'ACTIVE'})
const managementGroups=[{title:'BUSINESS',items:['Vehicle','Driver']},{title:'FINANCE',items:['Finance','Fixed Expenses']},{title:'OPERATIONS',items:['Renewals','Maintenance','Loans']},{title:'SYSTEM',items:['Settings']}]
const money=v=>v==null?'Unavailable':`₹${(Number(v)/100).toFixed(2)}`
const percent=v=>v==null?'Unavailable':`${(Number(v)*100).toFixed(1)}%`
const statusText=v=>v==='UNAVAILABLE'?'Calculation unavailable':v
const currentState=computed(()=>model.value?.currentState||{})
const fixedExpenses=computed(()=>model.value?.fixedExpenses||[])
const expenseBreakdown=computed(()=>model.value?.expenseBreakdown||model.value?.month?.expenseBreakdown||{})
const loanItems=computed(()=>{const v=loanModel.value;return Array.isArray(v)?v:(v?.loans||v?.items||v?.records||[])})
async function load(){loading.value=true;error.value='';try{model.value=await props.application.getAdminState(month.value);try{loanModel.value=await props.application.getLoanReadModel(month.value)}catch{loanModel.value=null}}catch(e){error.value=String(e?.message||e);model.value=null}finally{loading.value=false}}
function open(item){if(item==='Fixed Expenses'){section.value='fixed-expenses';return}emit('open',item)}
function goHome(){section.value='home';week.value=null} function goMonth(){section.value='month';week.value=null} function goFinance(){section.value='finance';week.value=null} function goManagement(){section.value='management';week.value=null}
function selectWeek(v){week.value=v;section.value='week'} function selectDay(){open('Timeline')}
function resetFixedExpenseForm(){fixedExpenseForm.value={name:'',category:'',amount:'',effective_from:new Date().toISOString().slice(0,10),status:'ACTIVE'};fixedExpenseEditing.value=null;fixedExpenseError.value=''}
function addFixedExpense(){resetFixedExpenseForm();fixedExpenseOpen.value=true}
function editFixedExpense(row){fixedExpenseEditing.value=row;fixedExpenseError.value='';fixedExpenseForm.value={name:row.name||'',category:row.category||'',amount:((Number(row.amount_paise||0))/100).toFixed(2),effective_from:String(row.effective_from||'').slice(0,10),status:row.status||'ACTIVE'};fixedExpenseOpen.value=true}
function cancelFixedExpense(){fixedExpenseOpen.value=false;resetFixedExpenseForm()}
async function saveFixedExpense(){fixedExpenseBusy.value=true;fixedExpenseError.value='';try{const value={name:fixedExpenseForm.value.name,category:fixedExpenseForm.value.category,amount_paise:Math.round(Number(fixedExpenseForm.value.amount)*100),effective_from:fixedExpenseForm.value.effective_from,status:fixedExpenseForm.value.status};if(fixedExpenseEditing.value)await props.application.fixedExpenses.update(fixedExpenseEditing.value.id,value);else await props.application.fixedExpenses.create(value);await load();cancelFixedExpense()}catch(e){fixedExpenseError.value=String(e?.message||e)}finally{fixedExpenseBusy.value=false}}
async function toggleFixedExpense(row){try{if(row.status==='ACTIVE')await props.application.fixedExpenses.deactivate(row.id);else await props.application.fixedExpenses.activate(row.id);await load()}catch(e){fixedExpenseError.value=String(e?.message||e)}}
watch(()=>props.online,load);onMounted(load)
</script>
<template>
<section class="kfe-admin" aria-labelledby="admin-title">
<header class="kfe-admin__header"><button v-if="section!=='home'" type="button" class="kfe-secondary-action" @click="section==='week'?goMonth():goHome()">‹ Admin</button><p class="kfe-eyebrow">BACK-OFFICE</p><h1 id="admin-title">Admin</h1><p class="kfe-destination-subtitle">Administrative command center. Driver operations remain in Work, Performance and Timeline.</p></header>
<p v-if="loading" class="kfe-boundary-note" role="status">Loading authoritative state…</p><p v-if="error" class="kfe-error-note" role="alert">{{error}}</p>
<template v-if="!loading && model">
<template v-if="section==='home'">
<section class="kfe-admin-section"><h2>CURRENT STATE</h2><div class="kfe-admin-grid"><article><span>Vehicle</span><strong>{{currentState.vehicle?.registration_number||'Unavailable'}}</strong></article><article><span>Connection</span><strong>{{online?'Online':'Offline'}}</strong></article><article><span>Driver</span><strong>{{currentState.driver?.name||'None assigned'}}</strong></article><article><span>Odometer</span><strong>{{currentState.odometer==null?'Unavailable':`${currentState.odometer} km`}}</strong></article></div></section>
<section class="kfe-admin-section"><h2>OPERATING POSITION</h2><div class="kfe-finance-tiles"><article><strong>{{money(model.month?.revenuePaise)}}</strong><span>Revenue</span></article><article><strong>{{money(model.month?.costsPaise)}}</strong><span>Business Cost</span></article><article><strong>{{money(model.month?.profitPaise)}}</strong><span>Operating Result</span></article></div></section>
<section class="kfe-admin-section"><h2>INSIGHT</h2><article class="kfe-admin-card"><strong>{{model.insight?.title||'Operational insight'}}</strong><p>{{model.insight?.message||'Administrative interpretation remains limited to authoritative records.'}}</p></article></section>
<section class="kfe-admin-section"><h2>EXPENSE BREAKDOWN</h2><div class="kfe-admin-grid"><article><span>Fuel</span><strong>{{money(expenseBreakdown.fuelPaise)}}</strong></article><article><span>Maintenance</span><strong>{{money(expenseBreakdown.maintenancePaise)}}</strong></article><article><span>Other</span><strong>{{money(expenseBreakdown.otherPaise)}}</strong></article><article><span>Total Running Cost</span><strong>{{money(model.month?.costsPaise)}}</strong></article></div><p class="kfe-boundary-note">Breakdown values are displayed only when supplied by the authoritative read model; the presentation layer does not calculate them.</p></section>
<section class="kfe-admin-section"><h2>LOAN STATUS</h2><div v-if="loanItems.length" class="kfe-admin-list"><article v-for="loan in loanItems" :key="loan.id||loan.loanId||loan.name" class="kfe-admin-card"><strong>{{loan.name||loan.lender||loan.loanNumber||'Loan'}}</strong><p>Remaining balance: {{money(loan.remainingBalancePaise??loan.remaining_balance_paise??loan.balancePaise)}}</p><p>EMI: {{money(loan.emiPaise??loan.emi_paise)}} · {{loan.status||'Active'}}</p></article></div><p v-else class="kfe-boundary-note">No authoritative loan status is currently available.</p></section>
<section class="kfe-admin-section"><h2>ATTENTION</h2><article v-for="item in model.attention" :key="item.id||item.message" class="kfe-admin-card"><strong>{{item.title||'Action required'}}</strong><p>{{item.message}}</p></article><p v-if="!model.attention.length" class="kfe-boundary-note">No action required right now.</p></section>
<section class="kfe-admin-section"><h2>PROFITABILITY</h2><article class="kfe-admin-card"><strong>{{statusText(model.profitability.status)}}</strong><div class="kfe-position-line"><span>LOSS</span><span>●</span><span>PROFIT</span></div><dl><div><dt>Profit/KM</dt><dd>{{money(model.profitability.profitPerKmPaise)}}</dd></div><div><dt>Cost/KM</dt><dd>{{money(model.profitability.costPerKmPaise)}}</dd></div><div><dt>Margin</dt><dd>{{percent(model.profitability.marginPaise)}}</dd></div></dl></article></section>
<section class="kfe-admin-section"><h2>BREAK-EVEN</h2><article class="kfe-admin-card"><strong>{{statusText(model.breakEven.status)}}</strong><dl><div><dt>Break-even</dt><dd>{{money(model.breakEven.breakEvenPaise)}}</dd></div><div><dt>Current</dt><dd>{{money(model.breakEven.currentPaise)}}</dd></div><div><dt>Remaining</dt><dd>{{money(model.breakEven.remainingPaise)}}</dd></div></dl></article></section>
<section class="kfe-record-gateway" aria-label="Record or Entry"><div><span class="kfe-card-label">RECORD / ENTRY</span><strong>Record an authoritative business event</strong><p>Choose the record directly; no Data Centre step.</p></div><div class="kfe-record-grid"><button type="button" @click="open('Revenue')">Revenue</button><button type="button" @click="open('Expenses')">Expense</button><button type="button" @click="open('Maintenance')">Maintenance</button><button type="button" @click="open('Fuel')">Fuel</button><button type="button" @click="open('Loans')">Loan</button><button type="button" @click="open('Historical Entries')">Historical Entry</button></div></section>
<div class="kfe-admin-actions"><button class="kfe-primary-action" type="button" @click="goMonth">Month View</button><button class="kfe-secondary-action" type="button" @click="goFinance">Finance</button><button class="kfe-secondary-action" type="button" @click="goManagement">Management</button><button class="kfe-secondary-action" type="button" @click="open('Timeline')">View Timeline</button></div>
</template>
<template v-else-if="section==='month'"><section class="kfe-admin-section"><label class="kfe-form-label" for="admin-month">Month</label><input id="admin-month" v-model="month" type="month" @change="load"></section><section class="kfe-admin-section"><h2>{{month}} · PERIOD OVERVIEW</h2><div class="kfe-admin-grid"><article><span>Revenue</span><strong>{{money(model.month.revenuePaise)}}</strong></article><article><span>Business Cost</span><strong>{{money(model.month.costsPaise)}}</strong></article><article><span>Operating Result</span><strong>{{money(model.month.profitPaise)}}</strong></article><article><span>Business KM</span><strong>{{model.month.businessKm==null?'Unavailable':`${model.month.businessKm} km`}}</strong></article></div></section><section class="kfe-admin-section"><h2>EXPENSE BREAKDOWN</h2><div class="kfe-admin-grid"><article><span>Fuel</span><strong>{{money(expenseBreakdown.fuelPaise)}}</strong></article><article><span>Maintenance</span><strong>{{money(expenseBreakdown.maintenancePaise)}}</strong></article><article><span>Other</span><strong>{{money(expenseBreakdown.otherPaise)}}</strong></article></div></section><section class="kfe-admin-section"><h2>LOAN STATUS</h2><p class="kfe-boundary-note">{{loanItems.length?`${loanItems.length} authoritative loan record(s) available.`:'No authoritative loan status is currently available.'}}</p></section><section class="kfe-admin-section"><h2>WEEKLY</h2><div class="kfe-admin-list"><button v-for="item in model.weekly" :key="item.week" type="button" @click="selectWeek(item.week)"><span>Week {{item.week}}</span><span>View Week ›</span></button></div></section><section class="kfe-admin-section"><h2>TIMELINE</h2><button class="kfe-list-action" type="button" @click="open('Timeline')"><span>Month timeline</span><span>View Month Timeline ›</span></button></section></template>
<template v-else-if="section==='week'"><section class="kfe-admin-section"><h2>WEEK {{week}}</h2><article class="kfe-admin-card"><p>Weekly values are supplied by the application read model. The presentation layer does not calculate financial results.</p></article></section><section class="kfe-admin-section"><h2>DAYS</h2><div class="kfe-admin-list"><button v-for="day in 7" :key="day" type="button" @click="selectDay"><span>Day {{day}}</span><span>View Day ›</span></button></div></section><button class="kfe-list-action" type="button" @click="open('Timeline')"><span>Week timeline</span><span>View Week Timeline ›</span></button></template>
<template v-else-if="section==='finance'"><section class="kfe-admin-section"><h2>FINANCE</h2><p class="kfe-boundary-note">Derived, read-only financial dashboard. Correct source records instead of editing financial results here.</p><div class="kfe-finance-tiles"><article><strong>{{money(model.month.revenuePaise)}}</strong><span>Revenue</span></article><article><strong>{{money(model.month.costsPaise)}}</strong><span>Business Cost</span></article><article><strong>{{money(model.month.profitPaise)}}</strong><span>Operating Result</span></article><article><strong>{{money(model.profitability.profitPerKmPaise)}}</strong><span>Profit/KM</span></article><article><strong>{{money(model.profitability.costPerKmPaise)}}</strong><span>Cost/KM</span></article><article><strong>{{money(model.breakEven.breakEvenPaise)}}</strong><span>Break-even</span></article></div></section><section class="kfe-admin-section"><label class="kfe-form-label" for="finance-month">Month</label><input id="finance-month" v-model="month" type="month" @change="load"></section></template>
<template v-else-if="section==='management'"><section v-for="group in managementGroups" :key="group.title" class="kfe-admin-section"><h2>{{group.title}}</h2><div class="kfe-admin-list"><button v-for="item in group.items" :key="item" type="button" @click="open(item)"><span>{{item}}</span><span>›</span></button></div></section></template>
<template v-else-if="section==='fixed-expenses'"><section class="kfe-admin-section"><h2>FIXED EXPENSES</h2><p class="kfe-boundary-note">Lifecycle-managed recurring business obligations. Changes are persisted through the application boundary.</p><button class="kfe-primary-action" type="button" @click="addFixedExpense">Add fixed expense</button><div class="kfe-admin-list"><article v-for="row in fixedExpenses" :key="row.id" class="kfe-admin-card"><div><strong>{{row.name}}</strong><p>{{row.category}} · {{money(row.monthly_amount_paise??row.amount_paise)}} / month</p><p>{{row.effective_from}} · {{row.status}}</p></div><div class="kfe-admin-actions"><button class="kfe-secondary-action" type="button" @click="editFixedExpense(row)">Edit</button><button class="kfe-secondary-action" type="button" @click="toggleFixedExpense(row)">{{row.status==='ACTIVE'?'Deactivate':'Activate'}}</button></div></article><p v-if="!fixedExpenses.length" class="kfe-boundary-note">No fixed expenses configured.</p></div></section>
<div v-if="fixedExpenseOpen" class="kfe-admin-card"><h2>{{fixedExpenseEditing?'EDIT FIXED EXPENSE':'ADD FIXED EXPENSE'}}</h2><label class="kfe-form-label" for="fixed-name">Name</label><input id="fixed-name" v-model="fixedExpenseForm.name" type="text"><label class="kfe-form-label" for="fixed-category">Category</label><input id="fixed-category" v-model="fixedExpenseForm.category" type="text"><label class="kfe-form-label" for="fixed-amount">Monthly amount</label><input id="fixed-amount" v-model="fixedExpenseForm.amount" type="number" inputmode="decimal"><label class="kfe-form-label" for="fixed-effective">Effective from</label><input id="fixed-effective" v-model="fixedExpenseForm.effective_from" type="date"><label class="kfe-form-label" for="fixed-status">Status</label><select id="fixed-status" v-model="fixedExpenseForm.status"><option value="ACTIVE">ACTIVE</option><option value="INACTIVE">INACTIVE</option></select><p v-if="fixedExpenseError" class="kfe-error-note" role="alert">{{fixedExpenseError}}</p><div class="kfe-admin-actions"><button class="kfe-primary-action" type="button" :disabled="fixedExpenseBusy" @click="saveFixedExpense">Save</button><button class="kfe-secondary-action" type="button" :disabled="fixedExpenseBusy" @click="cancelFixedExpense">Cancel</button></div></div></template>
</template>
</section>
</template>
<style scoped>
.kfe-admin{padding:16px;display:grid;gap:16px;padding-bottom:150px}.kfe-admin__header{display:grid;gap:6px}.kfe-admin-section{display:grid;gap:10px}.kfe-admin-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.kfe-admin-grid article,.kfe-admin-card,.kfe-record-gateway{padding:14px;border:1px solid var(--kfe-ui-border);border-radius:16px;background:var(--kfe-ui-surface);display:grid;gap:7px}.kfe-admin-grid span,.kfe-admin-card span{font-size:.8rem;color:var(--kfe-muted-text)}.kfe-admin-grid strong{font-size:1.05rem}.kfe-admin-card p{margin:0;color:var(--kfe-muted-text);line-height:1.4}.kfe-admin-card dl{display:grid;gap:8px}.kfe-admin-card dl div{display:flex;justify-content:space-between;gap:12px}.kfe-admin-card dt{color:var(--kfe-muted-text)}.kfe-admin-card dd{margin:0;font-weight:800}.kfe-position-line{display:flex;justify-content:space-between;align-items:center;font-size:.78rem}.kfe-admin-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.kfe-admin-list{display:grid;gap:8px}.kfe-admin-list button,.kfe-finance-tiles button{min-height:52px;border:1px solid var(--kfe-ui-border);border-radius:12px;background:var(--kfe-ui-surface);color:var(--kfe-ui-text);padding:12px;display:flex;justify-content:space-between;align-items:center;text-align:left}.kfe-finance-tiles{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.kfe-finance-tiles article{min-height:84px;padding:12px;border:1px solid var(--kfe-ui-border);border-radius:14px;background:var(--kfe-ui-surface);display:grid;align-content:center;gap:4px}.kfe-finance-tiles strong{font-size:1.05rem}.kfe-finance-tiles span{font-size:.72rem;color:var(--kfe-muted-text)}.kfe-record-gateway{position:fixed;left:10px;right:10px;bottom:78px;z-index:940;box-shadow:var(--kfe-ui-shadow);border-color:var(--kfe-accent)}.kfe-record-gateway strong{font-size:.95rem}.kfe-record-gateway p{margin:2px 0 0;color:var(--kfe-muted-text);font-size:.72rem}.kfe-record-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.kfe-record-grid button{min-height:44px;border:1px solid var(--kfe-ui-border);border-radius:11px;background:var(--kfe-ui-bg);color:var(--kfe-ui-text);font-weight:850;font-size:.72rem}.kfe-admin-card input,.kfe-admin-card select{min-height:48px;border:1px solid var(--kfe-ui-border);border-radius:10px;background:var(--kfe-ui-surface);color:var(--kfe-ui-text);padding:10px}@media(min-width:700px){.kfe-admin-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.kfe-finance-tiles{grid-template-columns:repeat(3,minmax(0,1fr))}.kfe-record-gateway{left:50%;right:auto;transform:translateX(-50%);width:min(680px,calc(100vw - 24px))}}
</style>
