<script setup>
import { computed, onMounted, ref } from 'vue';
import KfeFormShell from './KfeFormShell.vue';
const props=defineProps({application:{type:Object,required:true}});const emit=defineEmits(['back']);
const mode=ref(null),editingId=ref(null),drivers=ref([]),vehicles=ref([]),assignments=ref([]),message=ref(''),error=ref('');
const draft=ref({name:'',mobile:'',licence_number:'',licence_expiry:''});const assignmentDraft=ref({vehicle_id:'',start_date:'',reason:''});
const today=()=>new Date().toISOString().slice(0,10);
async function load(){drivers.value=await props.application.administrator.listDrivers();vehicles.value=await props.application.administrator.listVehicles();assignments.value=await props.application.administrator.listAssignments();}
function add(){editingId.value=null;draft.value={name:'',mobile:'',licence_number:'',licence_expiry:''};error.value='';message.value='';mode.value='edit';}
function edit(d){editingId.value=d.id;draft.value={name:d.name,mobile:d.mobile||'',licence_number:d.licence_number,licence_expiry:d.licence_expiry||''};error.value='';message.value='';mode.value='edit';}
function assign(d){editingId.value=d.id;assignmentDraft.value={vehicle_id:'',start_date:today(),reason:''};error.value='';message.value='';mode.value='assign';}
function deactivate(d){editingId.value=d.id;assignmentDraft.value={vehicle_id:'',start_date:today(),reason:''};error.value='';message.value='';mode.value='deactivate';}
async function saveDriver(value){try{error.value='';if(editingId.value)await props.application.administrator.updateDriver(editingId.value,value);else await props.application.administrator.createDriver(value);mode.value=null;message.value='Driver saved safely.';await load();}catch(e){error.value=e?.message||String(e);}}
async function saveAssignment(value){try{error.value='';await props.application.administrator.assignDriver({driver_id:editingId.value,...value});mode.value=null;message.value='Driver assigned safely.';await load();}catch(e){error.value=e?.message||String(e);}}
async function saveDeactivation(value){try{error.value='';await props.application.administrator.deactivateDriver(editingId.value,{date:value.start_date,reason:value.reason});mode.value=null;message.value='Driver deactivated safely.';await load();}catch(e){error.value=e?.message||String(e);}}
function close(){mode.value=null;error.value='';}
function currentVehicle(driverId){const a=assignments.value.find(x=>x.driver_id===driverId&&x.status==='ACTIVE'&&!x.end_date);return vehicles.value.find(v=>v.id===a?.vehicle_id)?.registration_number||'None';}
function licenceState(d){return d.licence_expiry&&d.licence_expiry<today()?'Expired':'Valid / not recorded';}
onMounted(load);
</script>
<template>
<section class="kfe-module-view" aria-labelledby="driver-title"><div class="kfe-module-heading"><button class="kfe-secondary-action kfe-back-action" type="button" @click="emit('back')">‹ Vehicle</button><p class="kfe-eyebrow">Administrator · Vehicle</p><h1 id="driver-title">Drivers</h1><p class="kfe-destination-subtitle">Driver master records and historical vehicle assignments.</p></div><p v-if="message" class="kfe-success-note" role="status">{{message}}</p><p v-if="error" class="kfe-error-note" role="alert">{{error}}</p><div class="kfe-form-actions"><button class="kfe-primary-action" type="button" @click="add">Add Driver</button></div>
<KfeFormShell v-if="mode==='edit'" :draft-key="`driver-${editingId||'new'}`" :title="editingId?'Edit Driver':'Add Driver'" subtitle="Half-filled entry is safe; final save enforces identity and licence rules." :initial-value="draft" @save="saveDriver" @discard="close"><template #default="{value}"><div class="kfe-form-field"><label class="kfe-form-label">Full Name <span class="kfe-required">Required</span></label><input v-model="value.name" class="kfe-form-input" autocomplete="name" /></div><div class="kfe-form-field"><label class="kfe-form-label">Mobile Number</label><input v-model="value.mobile" class="kfe-form-input" inputmode="tel" /></div><div class="kfe-form-field"><label class="kfe-form-label">Driving Licence Number <span class="kfe-required">Required</span></label><input v-model="value.licence_number" class="kfe-form-input" autocomplete="off" /></div><div class="kfe-form-field"><label class="kfe-form-label">Licence Expiry Date</label><input v-model="value.licence_expiry" class="kfe-form-input" type="date" /></div></template></KfeFormShell>
<KfeFormShell v-else-if="mode==='assign'" :draft-key="`driver-assignment-${editingId}`" title="Assign Driver to Vehicle" subtitle="A driver may have only one current vehicle." :initial-value="assignmentDraft" @save="saveAssignment" @discard="close"><template #default="{value}"><div class="kfe-form-field"><label class="kfe-form-label">Vehicle <span class="kfe-required">Required</span></label><select v-model="value.vehicle_id" class="kfe-form-input"><option value="">Select vehicle</option><option v-for="v in vehicles.filter(x=>x.lifecycle_status==='ACTIVE')" :key="v.id" :value="v.id">{{v.registration_number}} · {{v.make}} {{v.model}}</option></select></div><div class="kfe-form-field"><label class="kfe-form-label">Start Date <span class="kfe-required">Required</span></label><input v-model="value.start_date" class="kfe-form-input" type="date" /></div><div class="kfe-form-field"><label class="kfe-form-label">Reason</label><textarea v-model="value.reason" class="kfe-form-input" rows="3"></textarea></div></template></KfeFormShell>
<KfeFormShell v-else-if="mode==='deactivate'" :draft-key="`driver-deactivate-${editingId}`" title="Deactivate Driver" subtitle="Historical records and assignments are preserved." :initial-value="assignmentDraft" @save="saveDeactivation" @discard="close"><template #default="{value}"><div class="kfe-form-field"><label class="kfe-form-label">Effective Date <span class="kfe-required">Required</span></label><input v-model="value.start_date" class="kfe-form-input" type="date" /></div><div class="kfe-form-field"><label class="kfe-form-label">Reason</label><textarea v-model="value.reason" class="kfe-form-input" rows="3"></textarea></div></template></KfeFormShell>
<section v-else class="kfe-module-section"><h2>Driver register</h2><article v-for="driver in drivers" :key="driver.id" class="kfe-detail-card"><div class="kfe-detail-card__top"><div><span class="kfe-card-label">{{driver.licence_number}}</span><strong>{{driver.name}}</strong></div><span class="kfe-state-badge">{{driver.status==='ACTIVE'?'Active':'Inactive'}}</span></div><dl class="kfe-detail-list"><div><dt>Mobile</dt><dd>{{driver.mobile||'—'}}</dd></div><div><dt>Licence expiry</dt><dd>{{driver.licence_expiry||'Not recorded'}} · {{licenceState(driver)}}</dd></div><div><dt>Current vehicle</dt><dd>{{currentVehicle(driver.id)}}</dd></div></dl><div class="kfe-form-actions"><button class="kfe-secondary-action" type="button" @click="edit(driver)">Edit</button><button v-if="driver.status==='ACTIVE'" class="kfe-secondary-action" type="button" @click="assign(driver)">Assign / Reassign</button><button v-if="driver.status==='ACTIVE'" class="kfe-secondary-action" type="button" @click="deactivate(driver)">Deactivate</button></div></article><p v-if="!drivers.length" class="kfe-boundary-note">No drivers recorded yet.</p></section>
</section>
</template>
