<script setup>
import { ref, watch } from 'vue'
const props=defineProps({open:{type:Boolean,default:false},initialOdometer:{type:Number,default:null}})
const emit=defineEmits(['submit','cancel'])
const endOdometer=ref(''); const grossRevenue=ref(''); const notes=ref(''); const error=ref('')
watch(()=>props.open,(open)=>{if(open){endOdometer.value=props.initialOdometer==null?'':String(props.initialOdometer);grossRevenue.value='';notes.value='';error.value=''}})
function submit(){const end=Number(endOdometer.value);const revenue=Number(grossRevenue.value);if(!Number.isFinite(end)||end<0||!Number.isInteger(end)){error.value='Enter a valid whole-number final odometer reading.';return}if(!Number.isFinite(revenue)||revenue<0){error.value='Enter a valid gross revenue amount.';return}emit('submit',{endOdometer:end,grossRevenue:revenue,notes:notes.value.trim()})}
</script>
<template><div v-if="open" class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="end-shift-modal-title"><h2 id="end-shift-modal-title">End Shift</h2><p class="modal-copy">Capture the final operational figures before closing the shift.</p><label>Final Odometer<input v-model="endOdometer" type="number" min="0" step="1" inputmode="numeric" autocomplete="off" autofocus /></label><label>Gross Revenue (₹)<input v-model="grossRevenue" type="number" min="0" step="0.01" inputmode="numeric" autocomplete="off" /></label><label>Operational Notes<textarea v-model="notes" rows="4" maxlength="1000" placeholder="Optional notes"></textarea></label><p v-if="error" class="error" role="alert">{{error}}</p><div class="actions"><button type="button" class="secondary" @click="emit('cancel')">Cancel</button><button type="button" class="primary" @click="submit">End Shift</button></div></section></div></template>
<style scoped>.modal-backdrop{position:fixed;inset:0;z-index:1000;display:grid;place-items:center;padding:16px;background:rgb(0 0 0 / .55);overflow:auto}.modal{width:min(100%,460px);max-height:calc(100vh - 32px);overflow:auto;padding:20px;border:1px solid var(--kfe-ui-border);border-radius:20px;background:var(--kfe-ui-surface);color:var(--kfe-ui-text);box-shadow:var(--kfe-ui-shadow)}h2{margin:0 0 8px}.modal-copy{margin:0 0 18px;color:var(--kfe-muted-text)}label{display:grid;gap:8px;margin-top:14px;font-weight:800}input,textarea{width:100%;box-sizing:border-box;padding:14px;border:1px solid var(--kfe-ui-border);border-radius:12px;background:var(--kfe-ui-bg);color:inherit;font:inherit}textarea{resize:vertical}.error{color:var(--kfe-danger,#d92d20);font-weight:700}.actions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:18px}button{min-height:48px;border-radius:12px;padding:10px 14px;font-weight:850}.primary{border:1px solid var(--kfe-accent);background:var(--kfe-accent);color:#fff}.secondary{border:1px solid var(--kfe-ui-border);background:var(--kfe-ui-bg);color:inherit}</style>
