<script setup>
import { computed, ref } from 'vue'

const props=defineProps({leftLabel:{type:String,default:''},rightLabel:{type:String,default:''},leftAction:{type:String,default:''},rightAction:{type:String,default:''},leftDisabled:{type:Boolean,default:false},rightDisabled:{type:Boolean,default:false},disabled:{type:Boolean,default:false},shell:{type:String,default:'driver'},activeState:{type:String,default:''}})
const emit=defineEmits(['swipe'])
const startX=ref(0),progress=ref(0),capturing=ref(false),dragging=ref(false),activePointer=ref(null),handleX=ref(0),dragDirection=ref(1)
function normalizeLabel(label){return String(label||'').replace(/^\s*<+\s*/,'').replace(/\s*>+\s*$/,'').trim()}
const leftText=computed(()=>normalizeLabel(props.leftLabel)),rightText=computed(()=>normalizeLabel(props.rightLabel)),isDual=computed(()=>Boolean(leftText.value&&rightText.value))
const barStyle=computed(()=>({'--swipe-progress':`${progress.value}%`,'--swipe-handle-x':`${handleX.value}px`,'--swipe-direction':dragDirection.value,'--swipe-state':props.activeState||'default','--swipe-accent':'var(--kfe-ui-accent)','--swipe-bg':'var(--kfe-ui-bg)','--swipe-surface':'var(--kfe-ui-surface)'}))
function setProgress(value,width,direction=1){const next=Math.max(0,Math.min(100,value));progress.value=next;const handleWidth=68;const travel=Math.max(0,width-handleWidth-10);handleX.value=isDual.value?(width-handleWidth)/2+(travel/2)*(next/100)*direction:5+(travel)*(next/100)}
function down(e){if(props.disabled||e.button!==undefined&&e.button!==0)return;activePointer.value=e.pointerId;startX.value=e.clientX;dragDirection.value=1;setProgress(0,e.currentTarget.clientWidth);capturing.value=true;dragging.value=true;e.currentTarget.setPointerCapture?.(e.pointerId)}
function move(e){if(!capturing.value||e.pointerId!==activePointer.value)return;const w=Math.max(1,e.currentTarget.clientWidth),dx=e.clientX-startX.value;dragDirection.value=dx<0?-1:1;const distance=isDual.value?Math.abs(dx)/(w/2)*100:Math.abs(dx)/w*100;setProgress(distance,w,dragDirection.value)}
function finish(e){if(!capturing.value||e.pointerId!==activePointer.value)return;const dx=e.clientX-startX.value,left=dx<0,threshold=progress.value>=70,action=left?props.leftAction:props.rightAction,blocked=props.disabled||(left?props.leftDisabled:props.rightDisabled);capturing.value=false;dragging.value=false;activePointer.value=null;e.currentTarget.releasePointerCapture?.(e.pointerId);if(threshold&&action&&!blocked){setProgress(100,e.currentTarget.clientWidth,left?-1:1);emit('swipe',action);setTimeout(()=>setProgress(0,e.currentTarget.clientWidth),140)}else setProgress(0,e.currentTarget.clientWidth)}
</script>
<template><div class="kfe-swipe-bar" :class="{'is-disabled':disabled,'is-dual':isDual,'is-dual-left':isDual&&dragDirection<0,'is-dragging':dragging}" :data-shell="shell" :data-state="activeState" :style="barStyle" :aria-disabled="disabled" aria-valuemin="0" aria-valuemax="100" :aria-valuenow="Math.round(progress)" role="slider" :aria-label="[leftText,rightText].filter(Boolean).join(' or ')" @pointerdown="down" @pointermove="move" @pointerup="finish" @pointercancel="finish"><span class="kfe-swipe-progress" aria-hidden="true"></span><span class="kfe-swipe-edge-glow" aria-hidden="true"></span><span v-if="leftText" class="kfe-swipe-left" :class="{'is-action-disabled':leftDisabled}"><b>←</b>{{leftText}}</span><span v-if="rightText" class="kfe-swipe-right" :class="{'is-action-disabled':rightDisabled}">{{rightText}}<b>→</b></span><span class="kfe-swipe-label-overlay" aria-hidden="true">{{leftText&&rightText?'Swipe to act':leftText||rightText}}</span><span class="kfe-swipe-chevrons" aria-hidden="true">›››</span><span class="kfe-swipe-handle" aria-hidden="true"><i></i>›</span><span class="kfe-swipe-gps" aria-hidden="true">GPS • {{new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}}</span></div></template>

<style>
.kfe-swipe-bar{--swipe-accent:var(--kfe-ui-accent,#38bdf8);--swipe-bg:var(--kfe-ui-bg,#0f172a);--swipe-surface:var(--kfe-ui-surface,#111827);position:relative;min-height:78px!important;height:78px!important;border:1px solid color-mix(in srgb,var(--swipe-accent) 48%,var(--kfe-ui-border,#ffffff33))!important;border-radius:24px!important;background:linear-gradient(135deg,color-mix(in srgb,var(--swipe-surface) 88%,var(--swipe-accent) 12%),color-mix(in srgb,var(--swipe-bg) 82%,var(--swipe-accent) 18%))!important;box-shadow:0 18px 42px color-mix(in srgb,var(--swipe-accent) 20%,transparent),inset 0 1px 0 color-mix(in srgb,white 18%,transparent),inset 0 -1px 0 color-mix(in srgb,var(--swipe-accent) 22%,transparent)!important;overflow:hidden}
.kfe-swipe-bar::after{content:"";position:absolute;inset:1px;border-radius:23px;pointer-events:none;background:linear-gradient(110deg,color-mix(in srgb,var(--swipe-accent) 16%,transparent),transparent 38%,color-mix(in srgb,var(--swipe-accent) 10%,transparent));opacity:.9}
.kfe-swipe-progress{position:absolute;z-index:0;top:0;bottom:0;width:50%;border-radius:inherit;background:linear-gradient(90deg,color-mix(in srgb,var(--swipe-accent) 16%,transparent),color-mix(in srgb,var(--swipe-accent) 34%,transparent));box-shadow:inset -1px 0 0 color-mix(in srgb,var(--swipe-accent) 72%,transparent),0 0 24px color-mix(in srgb,var(--swipe-accent) 22%,transparent);transition:transform 90ms linear,scale 90ms linear,width 90ms linear;pointer-events:none;transform-origin:left center;left:0;scale:var(--swipe-progress,0)}
.kfe-swipe-bar:not(.is-dual) .kfe-swipe-progress{left:0;width:var(--swipe-progress,0%);scale:1;transform:none}
.kfe-swipe-bar.is-dual .kfe-swipe-progress{left:50%;width:50%;scale:calc(var(--swipe-progress,0%) / 100);transform:none}
.kfe-swipe-bar.is-dual.is-dual-left .kfe-swipe-progress{transform:translateX(-100%);transform-origin:right center}
.kfe-swipe-edge-glow{position:absolute;z-index:1;top:7px;bottom:7px;left:calc(var(--swipe-progress,0%) - 18px);width:36px;border-radius:18px;background:radial-gradient(circle,color-mix(in srgb,var(--swipe-accent) 78%,transparent),transparent 68%);filter:blur(7px);opacity:calc(.15 + (var(--swipe-progress,0%) / 100%));pointer-events:none;transition:left 90ms linear}
.kfe-swipe-bar.is-dual .kfe-swipe-edge-glow{left:calc(50% + (var(--swipe-progress,0%) * .5% * var(--swipe-direction)) - 18px)}
.kfe-swipe-handle{position:absolute!important;left:5px!important;top:5px!important;bottom:5px!important;width:68px!important;transform:translateX(var(--swipe-handle-x,0px));border-radius:19px!important;background:linear-gradient(145deg,color-mix(in srgb,var(--swipe-accent) 74%,white 26%),color-mix(in srgb,var(--swipe-accent) 78%,black 22%))!important;border:1px solid color-mix(in srgb,white 42%,var(--swipe-accent))!important;color:white!important;font-size:1.7rem!important;box-shadow:0 7px 22px color-mix(in srgb,var(--swipe-accent) 36%,black 34%),inset 0 1px 0 rgba(255,255,255,.35)!important;transition:transform 90ms linear}
.kfe-swipe-handle i{position:absolute;inset:9px;border-radius:13px;border:1px solid rgba(255,255,255,.22);opacity:.65}
.kfe-swipe-left,.kfe-swipe-right{font-size:.95rem!important;text-shadow:0 1px 10px color-mix(in srgb,var(--swipe-accent) 25%,transparent)}
.kfe-swipe-left b,.kfe-swipe-right b{color:var(--swipe-accent);filter:drop-shadow(0 0 7px color-mix(in srgb,var(--swipe-accent) 55%,transparent))}
.kfe-swipe-label-overlay{font-size:.72rem!important;letter-spacing:.12em!important;color:color-mix(in srgb,var(--kfe-ui-text,#fff) 78%,var(--swipe-accent))!important}
.kfe-swipe-chevrons{font-size:1.3rem!important;letter-spacing:.2em!important;color:color-mix(in srgb,var(--swipe-accent) 78%,white)!important;text-shadow:0 0 14px color-mix(in srgb,var(--swipe-accent) 48%,transparent)}
.kfe-swipe-gps{font-size:.58rem;letter-spacing:.04em;opacity:.45;color:var(--kfe-ui-text,#fff)}
.kfe-swipe-bar[data-shell="fleet"]{--swipe-accent:color-mix(in srgb,var(--kfe-ui-accent,#a78bfa) 78%,#a78bfa)}
.kfe-swipe-bar[data-shell="delivery"]{--swipe-accent:color-mix(in srgb,var(--kfe-ui-accent,#34d399) 78%,#34d399)}
.kfe-swipe-bar[data-shell="driver"]{--swipe-accent:color-mix(in srgb,var(--kfe-ui-accent,#38bdf8) 78%,#38bdf8)}
.kfe-swipe-bar[data-state="close"]{--swipe-accent:color-mix(in srgb,var(--kfe-ui-accent,#fb7185) 72%,#fb7185)}
.kfe-swipe-bar.is-dragging .kfe-swipe-edge-glow{filter:blur(5px);opacity:.95}
.kfe-swipe-bar.is-dual .kfe-swipe-handle{transition:transform 70ms linear}
@media(max-width:600px){.kfe-swipe-bar{min-height:76px!important;height:76px!important;border-radius:22px!important;padding:0 14px!important}.kfe-swipe-handle{width:64px!important}.kfe-swipe-gps{display:none}.kfe-swipe-label-overlay{font-size:.66rem!important}}
@media(prefers-reduced-motion:reduce){.kfe-swipe-progress,.kfe-swipe-edge-glow,.kfe-swipe-handle{transition:none!important}}
</style>