<script setup>
import { computed, ref } from 'vue'
const props=defineProps({leftLabel:{type:String,default:''},rightLabel:{type:String,default:''},leftAction:{type:String,default:''},rightAction:{type:String,default:''},leftDisabled:{type:Boolean,default:false},rightDisabled:{type:Boolean,default:false},disabled:{type:Boolean,default:false}})
const emit=defineEmits(['swipe'])
const startX=ref(0),progress=ref(0),capturing=ref(false),dragging=ref(false),activePointer=ref(null)
function normalizeLabel(label){return String(label||'').replace(/^\s*<+\s*/,'').replace(/\s*>+\s*$/,'').trim()}
const leftText=computed(()=>normalizeLabel(props.leftLabel)),rightText=computed(()=>normalizeLabel(props.rightLabel))
const barStyle=computed(()=>({'--swipe-progress':`${progress.value}%`,'--swipe-handle-x':`${Math.max(0,Math.min(100,progress.value))}%`}))
function queueTelemetry(action){const capturedAt=new Date().toISOString(),event={action:String(action||''),capturedAt,latitude:null,longitude:null,accuracy:null,positionCapturedAt:null};try{const q=JSON.parse(localStorage.getItem('kfe:telemetry-buffer')||'[]');q.push(event);localStorage.setItem('kfe:telemetry-buffer',JSON.stringify(q.slice(-100)))}catch{};try{navigator.geolocation?.getCurrentPosition(p=>{event.latitude=p.coords.latitude;event.longitude=p.coords.longitude;event.accuracy=p.coords.accuracy;event.positionCapturedAt=new Date(p.timestamp||Date.now()).toISOString();try{const q=JSON.parse(localStorage.getItem('kfe:telemetry-buffer')||'[]');const i=q.map(x=>x.capturedAt).lastIndexOf(capturedAt);if(i>=0){q[i]=event;localStorage.setItem('kfe:telemetry-buffer',JSON.stringify(q.slice(-100)))}}catch{}},()=>{},{enableHighAccuracy:false,maximumAge:30000,timeout:1500})}catch{}}
function down(e){if(props.disabled)return;activePointer.value=e.pointerId;startX.value=e.clientX;progress.value=0;capturing.value=true;dragging.value=true;e.currentTarget.setPointerCapture?.(e.pointerId)}
function move(e){if(!capturing.value||e.pointerId!==activePointer.value)return;const w=Math.max(1,e.currentTarget.clientWidth);progress.value=Math.max(0,Math.min(100,Math.abs(e.clientX-startX.value)/w*100))}
function finish(e){if(!capturing.value||e.pointerId!==activePointer.value)return;const dx=e.clientX-startX.value,left=dx<0,threshold=progress.value>=70,action=left?props.leftAction:props.rightAction,blocked=props.disabled||(left?props.leftDisabled:props.rightDisabled);capturing.value=false;dragging.value=false;activePointer.value=null;e.currentTarget.releasePointerCapture?.(e.pointerId);if(threshold&&action&&!blocked){progress.value=100;try{navigator.vibrate?.([30,50])}catch{};queueTelemetry(action);emit('swipe',action);setTimeout(()=>{progress.value=0},140)}else progress.value=0}
</script>
<template><div class="kfe-swipe-bar" :class="{'is-disabled':disabled,'is-dual':Boolean(leftText&&rightText),'is-dragging':dragging}" :style="barStyle" :aria-disabled="disabled" aria-valuemin="0" aria-valuemax="100" :aria-valuenow="Math.round(progress)" role="slider" :aria-label="[leftText,rightText].filter(Boolean).join(' or ')" @pointerdown="down" @pointermove="move" @pointerup="finish" @pointercancel="finish"><span v-if="leftText" class="kfe-swipe-left" :class="{'is-action-disabled':leftDisabled}"><b>←</b>{{leftText}}</span><span v-if="rightText" class="kfe-swipe-right" :class="{'is-action-disabled':rightDisabled}">{{rightText}}<b>→</b></span><span class="kfe-swipe-gps" aria-hidden="true">GPS • {{new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}}</span></div></template>
