<script setup>
import { computed, ref } from 'vue';
import KfeStatePanel from './KfeStatePanel.vue';
import { projectTimeline, deriveTimelineDistances, buildTimelineJourneyModel, summarizeOutstationJourneys, summarizeTimelineActivity, summarizeFuelActivity, timelineArea } from '../../js/ui/timeline.js';
import '../styles/timeline-horizons.css';

const props=defineProps({horizon:{type:String,default:'Day'},events:{type:Array,default:()=>[]}});
const emit=defineEmits(['edit']);
const locationFilter=ref('ALL'),locationMenuOpen=ref(false),longTermMode=ref('ALL'),fuelMode=ref('ALL');
function timeLabel(value){if(!value)return 'Time unavailable';const d=new Date(value);return Number.isFinite(d.getTime())?d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'Time unavailable';}
function dateLabel(value){if(!value)return '';const d=new Date(value);return Number.isFinite(d.getTime())?d.toLocaleDateString([], {day:'numeric',month:'short',year:'numeric'}):'Date unavailable';}
function monthLabel(value){if(!value)return 'Unknown period';const d=new Date(value);return Number.isFinite(d.getTime())?d.toLocaleDateString([], {month:'long',year:'numeric'}):'Unknown period';}
function dayKey(value){const d=new Date(value);return Number.isFinite(d.getTime())?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`:'unknown';}
function monthKey(value){const d=new Date(value);return Number.isFinite(d.getTime())?`${d.getFullYear()}-${d.getMonth()}`:'unknown';}
function isMumbaiArea(event){return timelineArea(event)==='MUMBAI';}
function isOutsideMumbai(event){return timelineArea(event)==='OUTSIDE';}
function isTrip(event){return String(event.type||'').toLowerCase().includes('trip');}
function iconFor(event){const type=String(event.type||'').toLowerCase();if(type.includes('fuel'))return '⛽';if(type.includes('maintenance'))return '🔧';if(type.includes('expense'))return '💳';if(type.includes('revenue'))return '💰';if(type.includes('loan'))return '🏦';if(type.includes('compliance')||type.includes('renew'))return '📄';if(type.includes('personal'))return '👤';if(type.includes('trip'))return '🚗';if(type.includes('shift')||type.includes('work'))return type.includes('end')?'🔴':'🟢';return '•';}
function eventLabel(event){const type=String(event.type||'Other');const lower=type.toLowerCase();if(lower==='start shift'||lower==='work session')return 'Work Session';if(lower.includes('start')&&lower.includes('shift'))return 'Work Started';if(lower.includes('end')&&lower.includes('shift'))return 'Work Ended';if(lower.includes('business trip'))return 'Business Trip';if(lower.includes('personal trip'))return 'Personal Trip';return type;}
function displayScope(event){return event.scope==='PERSONAL'?'Personal':event.scope==='BUSINESS'?'Business':'';}
function selectLocation(value){locationFilter.value=value;locationMenuOpen.value=false;}
function selectLongTermMode(value){longTermMode.value=value;}
function selectFuelMode(value){fuelMode.value=value;}
function fuelList(){if(fuelMode.value==='MUMBAI')return fuelSummary.value.mumbai;if(fuelMode.value==='OUTSTATION')return fuelSummary.value.outstation;if(fuelMode.value==='UNKNOWN')return fuelSummary.value.unknown;return [...fuelSummary.value.mumbai,...fuelSummary.value.outstation,...fuelSummary.value.unknown].sort((a,b)=>Date.parse(a.occurredAt)-Date.parse(b.occurredAt));}
function fuelLocationLabel(event){return event.locationName||'Location unavailable';}
function fuelAmount(event){return event.amount!==null&&event.amount!==undefined?`₹ ${Number(event.amount).toFixed(2)}`:'Amount unavailable';}
const projectedEvents=computed(()=>projectTimeline(props.events));
const chronologicallyDerivedEvents=computed(()=>deriveTimelineDistances(projectedEvents.value));
const journeyModel=computed(()=>buildTimelineJourneyModel(chronologicallyDerivedEvents.value));
const outstationSummary=computed(()=>summarizeOutstationJourneys(chronologicallyDerivedEvents.value));
const activitySummary=computed(()=>summarizeTimelineActivity(chronologicallyDerivedEvents.value));
const fuelSummary=computed(()=>summarizeFuelActivity(chronologicallyDerivedEvents.value));
const locations=computed(()=>Array.from(new Set(chronologicallyDerivedEvents.value.map(e=>String(e.locationName||'').trim()).filter(Boolean))).sort((a,b)=>a.localeCompare(b)));
const outsideLocations=computed(()=>locations.value.filter(location=>timelineArea({locationName:location})==='OUTSIDE'));
const filteredEvents=computed(()=>chronologicallyDerivedEvents.value.filter(event=>{const loc=event.locationName||'';if(locationFilter.value==='ALL')return true;if(locationFilter.value==='MUMBAI')return isMumbaiArea(event);if(locationFilter.value==='OUTSIDE')return isOutsideMumbai(event);return loc===locationFilter.value;}));
const displayEvents=computed(()=>filteredEvents.value.map((event,index)=>({...event,hasConnector:index<filteredEvents.value.length-1})));
const dayGroups=computed(()=>{const map=new Map();for(const event of displayEvents.value){const key=dayKey(event.occurredAt);if(!map.has(key))map.set(key,{key,date:event.occurredAt,events:[]});map.get(key).events.push(event);}return [...map.values()].sort((a,b)=>Date.parse(a.date)-Date.parse(b.date));});
const monthGroups=computed(()=>{const map=new Map();for(const event of displayEvents.value){const key=monthKey(event.occurredAt);if(!map.has(key))map.set(key,{key,date:event.occurredAt,events:[],distanceKm:0,destinations:new Set(),business:0,personal:0});const group=map.get(key);group.events.push(event);if(event.distanceKm!==null)group.distanceKm+=event.distanceKm;if(event.locationName)group.destinations.add(event.locationName);if(event.scope==='BUSINESS')group.business++;if(event.scope==='PERSONAL')group.personal++;}return [...map.values()].sort((a,b)=>Date.parse(a.date)-Date.parse(b.date)).map(g=>({...g,destinations:[...g.destinations].sort()}));});
const selectedDestinationSummary=computed(()=>outstationSummary.value.destinations);
const selectedMonthlyGroups=computed(()=>{const map=new Map();for(const event of chronologicallyDerivedEvents.value){const area=timelineArea(event);if(longTermMode.value==='MUMBAI'&&area!=='MUMBAI')continue;if(longTermMode.value==='OUTSTATION'&&area!=='OUTSIDE')continue;const key=monthKey(event.occurredAt);if(!map.has(key))map.set(key,{key,date:event.occurredAt,trips:0,events:0});const group=map.get(key);group.events++;if(isTrip(event))group.trips++;}return [...map.values()].sort((a,b)=>Date.parse(a.date)-Date.parse(b.date));});
const selectedLongTermJourneys=computed(()=>longTermMode.value==='OUTSTATION'?outstationSummary.value.journeys:[]);
const filterLabel=computed(()=>locationFilter.value==='ALL'?'All Locations':locationFilter.value==='MUMBAI'?'Mumbai Area':locationFilter.value==='OUTSIDE'?'Outside Mumbai':locationFilter.value);
const editableTypes=new Set(['Work Session','Business Trip','Personal Trip','Fuel','Revenue','Expense']);
function canEdit(event){return editableTypes.has(event.entityType)&&Boolean(event.entityId);}
function edit(event){if(canEdit(event))emit('edit',event);}
</script>

<template>
 <div class="kfe-timeline-view" :data-horizon="horizon">
  <div class="kfe-timeline-toolbar"><div><span class="kfe-timeline-toolbar-label">Location</span><strong>{{horizon==='Day'?'Journey history':horizon==='Week'?'Weekly journey overview':'Journey history & trends'}}</strong></div><div class="kfe-location-filter"><button type="button" class="kfe-location-trigger" :aria-expanded="locationMenuOpen" @click="locationMenuOpen=!locationMenuOpen"><span aria-hidden="true">📍</span><span>{{filterLabel}}</span><span class="kfe-location-chevron" aria-hidden="true">⌄</span></button><div v-if="locationMenuOpen" class="kfe-location-menu" role="menu"><div class="kfe-location-menu-section">ALL</div><button type="button" :class="{'is-selected':locationFilter==='ALL'}" @click="selectLocation('ALL')">All Locations</button><div class="kfe-location-menu-section">JOURNEY AREA</div><button type="button" :class="{'is-selected':locationFilter==='MUMBAI'}" @click="selectLocation('MUMBAI')">📍 Mumbai Area</button><button type="button" :class="{'is-selected':locationFilter==='OUTSIDE'}" @click="selectLocation('OUTSIDE')">🧭 Outside Mumbai</button><template v-if="outsideLocations.length"><div class="kfe-location-menu-section">OUTSIDE-MUMBAI LOCATIONS</div><button v-for="location in outsideLocations" :key="location" type="button" :class="{'is-selected':locationFilter===location}" @click="selectLocation(location)">📍 {{location}}</button></template></div></div></div>

  <template v-if="horizon==='Day'"><div v-if="displayEvents.length" class="kfe-journey-timeline"><div v-for="(event,index) in displayEvents" :key="event.id || `${event.type}:${event.occurredAt}:${index}`" class="kfe-journey-item"><div class="kfe-journey-rail" aria-hidden="true"><span class="kfe-journey-dot">{{iconFor(event)}}</span><span v-if="index<displayEvents.length-1" class="kfe-journey-line"></span></div><div class="kfe-journey-content"><div class="kfe-journey-time">{{timeLabel(event.occurredAt)}}</div><article class="kfe-journey-card"><div class="kfe-journey-card-heading"><div><strong>{{eventLabel(event)}}</strong><span v-if="displayScope(event)" class="kfe-scope-badge">{{displayScope(event)}}</span></div><button v-if="canEdit(event)" type="button" class="kfe-timeline-edit" @click="edit(event)">Edit</button></div><div v-if="event.locationName" class="kfe-journey-location"><span aria-hidden="true">📍</span><span>{{event.locationName}}</span><span v-if="event.gpsAvailable" class="kfe-gps-badge">GPS</span></div><p v-if="event.description" class="kfe-journey-description">{{event.description}}</p><div v-if="event.amount!==null" class="kfe-journey-value">₹ {{Number(event.amount).toFixed(2)}}</div></article><div v-if="event.distanceKm!==null" class="kfe-journey-distance"><span class="kfe-distance-arrow">↓</span><strong>{{event.distanceKm.toLocaleString()}} km</strong><span>journey distance</span></div></div></div></div></template>

  <template v-else-if="horizon==='Week'"><div v-if="dayGroups.length" class="kfe-week-timeline"><section v-for="group in dayGroups" :key="group.key" class="kfe-week-day-card"><header class="kfe-week-day-heading"><div><strong>{{dateLabel(group.date)}}</strong><span>{{group.events.length}} {{group.events.length===1?'event':'events'}}</span></div><span>{{group.events.filter(e=>isTrip(e)).length}} trips</span></header><div class="kfe-week-events"><div v-for="event in group.events" :key="event.id || `${event.type}:${event.occurredAt}`" class="kfe-week-event"><span class="kfe-week-event-icon" aria-hidden="true">{{iconFor(event)}}</span><div class="kfe-week-event-main"><div><strong>{{eventLabel(event)}}</strong><span v-if="displayScope(event)" class="kfe-scope-badge">{{displayScope(event)}}</span></div><span class="kfe-week-event-meta">{{timeLabel(event.occurredAt)}}<template v-if="event.locationName"> · {{event.locationName}}</template></span></div><span v-if="event.distanceKm!==null" class="kfe-week-event-distance">{{event.distanceKm.toLocaleString()}} km</span><button v-if="canEdit(event)" type="button" class="kfe-timeline-edit" @click="edit(event)">Edit</button></div></div></section></div></template>

  <template v-else><div v-if="displayEvents.length" class="kfe-longterm"><div class="kfe-longterm-summary"><div><span>Active days</span><strong>{{activitySummary.activeDays}}</strong></div><button type="button" class="kfe-longterm-summary-card" :class="{'is-selected':longTermMode==='ALL'}" @click="selectLongTermMode('ALL')"><span>Trips</span><strong>{{activitySummary.trips}}</strong></button><button type="button" class="kfe-longterm-summary-card" :class="{'is-selected':longTermMode==='OUTSTATION'}" @click="selectLongTermMode('OUTSTATION')"><span>Outstation journeys</span><strong>{{activitySummary.outstationJourneys}}</strong></button><div><span>Recorded distance</span><strong>{{chronologicallyDerivedEvents.reduce((sum,e)=>sum+(e.distanceKm||0),0).toLocaleString()}} km</strong></div></div>
   <section class="kfe-fuel-summary" aria-label="Fuel refuel summary"><header class="kfe-fuel-summary-heading"><div><span>⛽ FUEL</span><h2>Refuels by location</h2></div><strong>{{fuelSummary.total}} refuels</strong></header><div class="kfe-fuel-summary-grid"><button type="button" class="kfe-fuel-summary-card" :class="{'is-selected':fuelMode==='ALL'}" @click="selectFuelMode('ALL')"><span>Total refuels</span><strong>{{fuelSummary.total}}</strong><small>All recorded fuel events</small></button><button type="button" class="kfe-fuel-summary-card" :class="{'is-selected':fuelMode==='MUMBAI'}" @click="selectFuelMode('MUMBAI')"><span>Mumbai</span><strong>{{fuelSummary.mumbaiCount}}</strong><small>Tap for Mumbai fuel details</small></button><button type="button" class="kfe-fuel-summary-card" :class="{'is-selected':fuelMode==='OUTSTATION'}" @click="selectFuelMode('OUTSTATION')"><span>Outstation</span><strong>{{fuelSummary.outstationCount}}</strong><small>Tap for outstation fuel details</small></button></div><div v-if="fuelSummary.unknownCount" class="kfe-fuel-unclassified"><span>{{fuelSummary.unknownCount}} refuel{{fuelSummary.unknownCount===1?'':'s'}} without a classified location</span><button type="button" @click="selectFuelMode('UNKNOWN')">View unclassified</button></div><section v-if="fuelMode!=='ALL' || fuelSummary.total" class="kfe-fuel-detail-card"><header><div><span>{{fuelMode==='MUMBAI'?'MUMBAI FUEL':fuelMode==='OUTSTATION'?'OUTSTATION FUEL':fuelMode==='UNKNOWN'?'UNCLASSIFIED FUEL':'ALL FUEL'}}</span><h3>{{fuelList().length}} refuels</h3></div><button v-if="fuelMode!=='ALL'" type="button" class="kfe-fuel-back" @click="selectFuelMode('ALL')">All refuels</button></header><div v-if="fuelList().length" class="kfe-fuel-details-list"><article v-for="(fuel,index) in fuelList()" :key="fuel.id || `fuel:${fuel.occurredAt}:${index}`" class="kfe-fuel-detail-item"><div class="kfe-fuel-detail-icon" aria-hidden="true">⛽</div><div class="kfe-fuel-detail-main"><strong>{{dateLabel(fuel.occurredAt)}} · {{timeLabel(fuel.occurredAt)}}</strong><span>📍 {{fuelLocationLabel(fuel)}}</span><div class="kfe-fuel-detail-meta"><span>{{fuelAmount(fuel)}}</span><span v-if="fuel.quantity!==null&&fuel.quantity!==undefined">{{fuel.quantity}} {{fuel.unit||'kg'}}</span><span v-if="fuel.fuelType">{{fuel.fuelType}}</span><span v-if="fuel.vehicle">{{fuel.vehicle}}</span></div><small v-if="fuel.reference">Ref: {{fuel.reference}}</small></div><button v-if="canEdit(fuel)" type="button" class="kfe-timeline-edit" @click="edit(fuel)">Edit</button></article></div><KfeStatePanel v-else state="empty" title="No refuels in this category" message="Fuel events will appear here when authoritative fuel records with a location are available." /></section></section>
   <div class="kfe-longterm-split"><button type="button" class="kfe-longterm-activity-card" :class="{'is-selected':longTermMode==='MUMBAI'}" @click="selectLongTermMode('MUMBAI')"><span>Mumbai</span><strong>{{activitySummary.mumbaiTrips}} trips</strong><small>Tap to view Mumbai activity</small></button><button type="button" class="kfe-longterm-activity-card" :class="{'is-selected':longTermMode==='OUTSTATION'}" @click="selectLongTermMode('OUTSTATION')"><span>Outstation</span><strong>{{activitySummary.outstationJourneys}} journeys</strong><small>Tap to view destinations & journeys</small></button></div>
   <template v-if="longTermMode==='OUTSTATION'"><section v-if="selectedDestinationSummary.length" class="kfe-longterm-detail-card"><header><div><span>OUTSTATION DESTINATIONS</span><h2>Top outstation destinations</h2></div><strong>{{outstationSummary.count}} journeys</strong></header><div class="kfe-destination-rank"><button v-for="destination in selectedDestinationSummary" :key="destination.name" type="button" @click="selectLocation(destination.name)"><span>{{destination.name}}</span><strong>{{destination.count}}</strong></button></div></section><section v-if="selectedLongTermJourneys.length" class="kfe-outstation-journeys"><article v-for="(journey,index) in selectedLongTermJourneys" :key="journey.id" class="kfe-outstation-journey-card"><header><div><span>OUTSTATION JOURNEY #{{index+1}}</span><h2>{{journey.origin}} → {{journey.destination}} → Mumbai</h2></div><small>{{dateLabel(journey.startedAt)}}</small></header><div class="kfe-outstation-events"><div v-for="(event,eventIndex) in journey.events" :key="event.id || `${journey.id}:${eventIndex}`" class="kfe-outstation-event"><span class="kfe-outstation-event-icon">{{eventIndex===journey.events.length-1&&isMumbaiArea(event)?'↩️':iconFor(event)}}</span><span>{{eventIndex===journey.events.length-1&&isMumbaiArea(event)?'Return':eventLabel(event)}}</span><small v-if="event.locationName">{{event.locationName}}</small><button v-if="canEdit(event)" type="button" class="kfe-timeline-edit" @click="edit(event)">Edit</button></div></div></article></section></template>
   <template v-else-if="longTermMode==='MUMBAI'"><section class="kfe-longterm-detail-card"><header><div><span>MUMBAI ACTIVITY</span><h2>Mumbai trip activity</h2></div><strong>{{activitySummary.mumbaiTrips}} trips</strong></header><div class="kfe-longterm-month-list"><div v-for="group in selectedMonthlyGroups" :key="group.key"><span>{{monthLabel(group.date)}}</span><strong>{{group.trips}} trips</strong></div></div></section></template>
   <div v-else class="kfe-longterm-groups"><section v-for="group in monthGroups" :key="group.key" class="kfe-longterm-month"><header><div><span>Period</span><h2>{{monthLabel(group.date)}}</h2></div><strong>{{group.events.length}} events</strong></header><div class="kfe-longterm-metrics"><span>{{group.events.filter(e=>isTrip(e)).length}} trips</span><span>{{group.distanceKm.toLocaleString()}} km</span><span>{{group.business}} business</span><span>{{group.personal}} personal</span></div><div v-if="group.destinations.length" class="kfe-destination-list"><span v-for="destination in group.destinations" :key="destination">📍 {{destination}}</span></div></section></div>
  </div></template>
  <KfeStatePanel v-if="!displayEvents.length" state="empty" :title="`No ${horizon.toLowerCase()} events`" :message="locationFilter==='ALL'?'Authoritative KFE events will appear here when available.':'No events match this location filter.'" />
 </div>
</template>
<style scoped>
.kfe-timeline-edit{border:1px solid var(--kfe-border,#dfe4ea);background:var(--kfe-surface,#fff);border-radius:8px;padding:5px 9px;font-weight:700;cursor:pointer;white-space:nowrap}.kfe-journey-card-heading{display:flex;justify-content:space-between;align-items:flex-start;gap:10px}.kfe-fuel-summary{margin:18px 0 22px;padding:16px;border:1px solid var(--kfe-border,#dfe4ea);border-radius:16px;background:var(--kfe-surface,#fff)}
.kfe-fuel-summary-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.kfe-fuel-summary-heading span{font-size:.72rem;font-weight:800;letter-spacing:.08em}.kfe-fuel-summary-heading h2{margin:3px 0 0;font-size:1.05rem}.kfe-fuel-summary-heading>strong{font-size:.95rem;white-space:nowrap}.kfe-fuel-summary-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.kfe-fuel-summary-card{appearance:none;border:1px solid var(--kfe-border,#dfe4ea);border-radius:12px;background:transparent;text-align:left;padding:12px;cursor:pointer}.kfe-fuel-summary-card.is-selected{border-color:currentColor}.kfe-fuel-summary-card span,.kfe-fuel-summary-card small{display:block}.kfe-fuel-summary-card span{font-size:.78rem}.kfe-fuel-summary-card strong{display:block;font-size:1.35rem;margin:4px 0}.kfe-fuel-summary-card small{font-size:.7rem;opacity:.72}.kfe-fuel-unclassified{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-top:10px;font-size:.76rem}.kfe-fuel-unclassified button,.kfe-fuel-back{border:0;background:none;text-decoration:underline;cursor:pointer;padding:4px}.kfe-fuel-detail-card{margin-top:12px;padding:14px;border-radius:12px;background:color-mix(in srgb,currentColor 4%,transparent)}.kfe-fuel-detail-card>header{display:flex;justify-content:space-between;align-items:center;gap:12px}.kfe-fuel-detail-card header span{font-size:.7rem;font-weight:800;letter-spacing:.06em}.kfe-fuel-detail-card h3{margin:3px 0 0;font-size:1rem}.kfe-fuel-details-list{display:grid;gap:8px;margin-top:10px}.kfe-fuel-detail-item{display:flex;gap:10px;align-items:flex-start;padding:10px;border:1px solid var(--kfe-border,#dfe4ea);border-radius:10px;background:var(--kfe-surface,#fff)}.kfe-fuel-detail-icon{font-size:1.15rem}.kfe-fuel-detail-main{min-width:0;display:grid;gap:3px;flex:1}.kfe-fuel-detail-main>strong{font-size:.82rem}.kfe-fuel-detail-main>span{font-size:.76rem}.kfe-fuel-detail-meta{display:flex;flex-wrap:wrap;gap:8px;font-size:.74rem}.kfe-fuel-detail-main small{font-size:.68rem;opacity:.7}@media (max-width:640px){.kfe-fuel-summary-grid{grid-template-columns:1fr}.kfe-fuel-summary-heading{align-items:flex-start;flex-direction:column}.kfe-fuel-unclassified{align-items:flex-start;flex-direction:column}}
</style>
