<script setup>
import { computed, onMounted, ref, watch } from 'vue';
import KfeFormShell from './KfeFormShell.vue';import KfeFormField from './KfeFormField.vue';import FuelHistoryView from './FuelHistoryView.vue';
const props=defineProps({module:{type:String,required:true},fuelRecords:{type:Array,default:()=>[]},fuelHistoryOpen:{type:Boolean,default:false},application:{type:Object,required:true}});
const emit=defineEmits(['save-request','back','open','fuel-history-back','fuel-undo']);
const activeAction=ref('');const detail=ref('');const model=ref(null);
const definitions={Fuel:{title:'Fuel',subtitle:'Record fuel using the established KFE fuel model.',actions:['Add fuel','Fuel history']},Expenses:{title:'Expenses',subtitle:'One unified expense model for business expenses.',actions:['Add expense','Toll','Parking','Expense history']},Revenue:{title:'Revenue',subtitle:'Fast manual end-of-day revenue entry.',actions:['Enter today’s revenue','Revenue history']}};
const definition=computed(()=>definitions[props.module]);
const records=computed(()=>props.module==='Expenses'?(model.value?.expenseRecords||[]):(model.value?.revenueRecords||[]));
const formSpec=computed(()=>{if(props.module==='Fuel'&&activeAction.value==='Add fuel')return{title:'Add fuel',subtitle:'Use Work Quick Fuel for the authoritative fuel record.',fields:[]};if(props.module==='Expenses'&&['Add expense','Toll','Parking'].includes(activeAction.value))return{title:activeAction.value==='Add expense'?'Add expense':`Add ${activeAction.value.toLowerCase()}`,subtitle:'Use the unified expense model.',fields:[{id:'category',label:'Category',required:true,placeholder:'Select category'},{id:'date',label:'Date',type:'date',required:true},{id:'amount',label:'Amount',type:'number',required:true,placeholder:'0.00'},{id:'description',label:'Description',optional:true,placeholder:'Optional details'},{id:'reference',label:'Receipt / reference',optional:true,placeholder:'Optional reference'}]};if(props.module==='Revenue'&&activeAction.value==='Enter today’s revenue')return{title:'Enter today’s revenue',subtitle:'Manual end-of-day revenue entry.',fields:[{id:'amount',label:'Revenue amount',type:'number',required:true,placeholder:'0.00'},{id:'date',label:'Date',type:'date',required:true}]};return null;});
async function load(){try{model.value=await props.application.getAdminState();}catch{model.value=null;}}
function openAction(item){if(item==='Fuel history'){emit('open','Fuel history');return;}if(item==='Add fuel'){emit('open','Work');return;}if(['Expense history','Revenue history'].includes(item)){detail.value=item;void load();return;}if(formSpec.value)activeAction.value=item;else emit('open',item);}
function closeAction(){activeAction.value='';}function closeDetail(){detail.value='';}function onSave(value){emit('save-request',{module:props.module,action:activeAction.value,value});}
watch(()=>props.module,()=>{activeAction.value='';detail.value='';model.value=null;void load();});
onMounted(load);
</script>
<template>
<section v-if="module==='Fuel'&&fuelHistoryOpen"><FuelHistoryView :records="fuelRecords" @back="emit('fuel-history-back')" @undo="emit('fuel-undo',$event)" /></section>
<section v-else class="kfe-module-view" :data-module="module" aria-labelledby="money-title"><button class="kfe-secondary-action kfe-back-action" type="button" @click="detail?closeDetail():activeAction?closeAction():emit('back')">‹ {{detail?definition.title:activeAction?definition.title:'More'}}</button><template v-if="detail"><p class="kfe-eyebrow">Money</p><h1 id="money-title">{{detail}}</h1><p class="kfe-destination-subtitle">Authoritative records supplied by the application read model.</p><article class="kfe-detail-card"><strong>{{detail}}</strong><div v-if="records.length" class="kfe-module-list"><article v-for="row in records" :key="row.id" class="kfe-detail-card"><strong>{{row.description||row.category||row.type||'Record'}}</strong><p>{{row.date||row.business_date||row.recorded_at?.slice(0,10)}} · ₹{{(Number(row.amount_paise??row.cost_paise??0)/100).toFixed(2)}}</p></article></div><p v-else>No records recorded.</p></article></template><template v-else><p class="kfe-eyebrow">Money</p><h1 id="money-title">{{definition.title}}</h1><p class="kfe-destination-subtitle">{{definition.subtitle}}</p><KfeFormShell v-if="formSpec&&formSpec.fields.length" :draft-key="`${module}:${activeAction}`" :title="formSpec.title" :subtitle="formSpec.subtitle" @save="onSave"><template #default="{value}"><KfeFormField v-for="field in formSpec.fields" :key="field.id" v-bind="field" v-model="value[field.id]"/><p class="kfe-form-boundary-note">Save submits to the application boundary.</p></template></KfeFormShell><div v-else class="kfe-module-sections"><section class="kfe-module-section"><h2>Quick entry</h2><div class="kfe-module-list"><button v-for="item in definition.actions" :key="item" type="button" @click="openAction(item)"><span>{{item}}</span><span aria-hidden="true">›</span></button></div></section></div></template></section>
</template>
