<script setup>
import { ref, watch } from 'vue'
const props=defineProps({open:{type:Boolean,default:false},initialOdometer:{type:Number,default:null}})
const emit=defineEmits(['submit','cancel'])
const odometer=ref('')
const error=ref('')
watch(()=>props.open,(open)=>{if(open){odometer.value=props.initialOdometer==null?'':String(props.initialOdometer);error.value=''}})
function submit(){const value=Number(odometer.value);if(!Number.isFinite(value)||value<0||!Number.isInteger(value)){error.value='Enter a valid whole-number odometer reading.';return}emit('submit',{odometer:value})}
</script>
<template><div v-if="open" class="modal-backdrop" role="presentation"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="start-day-modal-title"><h2 id="start-day-modal-title">Start Day</h2><p class="modal-copy">Enter the vehicle's initial odometer reading.</p><label>Start odometer<input v-model="odometer" type="number" min="0" step="1" inputmode="numeric" autocomplete="off" autofocus /></label><p v-if="error" class="error" role="alert">{{error}}</p><div class="actions"><button type="button" class="secondary" @click="emit('cancel')">Cancel</button><button type="button" class="primary" @click="submit">Start Day</button></div></section></div></template>
<style scoped>.modal-backdrop{position:fixed;inset:0;z-index:1000;display:grid;place-items:center;padding:16px;background:rgb(0 0 0 / .55)}.modal{width:min(100%,440px);padding:20px;border:1px solid var(--kfe-ui-border);border-radius:20px;background:var(--kfe-ui-surface);color:var(--kfe-ui-text);box-shadow:var(--kfe-ui-shadow)}h2{margin:0 0 8px}.modal-copy{margin:0 0 18px;color:var(--kfe-muted-text)}label{display:grid;gap:8px;font-weight:800}input{width:100%;box-sizing:border-box;padding:14px;border:1px solid var(--kfe-ui-border);border-radius:12px;background:var(--kfe-ui-bg);color:inherit;font:inherit}.error{color:var(--kfe-danger,#d92d20);font-weight:700}.actions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:18px}button{min-height:48px;border-radius:12px;padding:10px 14px;font-weight:850}.primary{border:1px solid var(--kfe-accent);background:var(--kfe-accent);color:#fff}.secondary{border:1px solid var(--kfe-ui-border);background:var(--kfe-ui-bg);color:inherit}</style>
