<script setup>
import { computed, onMounted, ref } from 'vue';
const props=defineProps({application:{type:Object,required:true},initialTab:{type:String,default:'Vehicle'}});
const emit=defineEmits(['back']);
const tab=ref(props.initialTab);const vehicles=ref([]);const drivers=ref([]);const message=ref('');const error=ref('');const busy=ref(false);
const vehicleForm=ref({registration_number:'',make:'',model:'',variant:'',fuel_type:'CNG',acquisition_date:new Date().toISOString().slice(0,10),acquisition_type:'USED',acquisition_odometer:0,acquisition_cost:0});
const driverForm=ref({name:'',mobile:'',licence_number:'',licence_expiry:''});
const assignmentForm=ref({vehicle_id:'',driver_id:'',start_date:new Date().toISOString().slice(0,10),reason:''});
const admin=computed(()=>props.application.administrator);
async function refresh(){vehicles.value=await admin.value.listVehicles();drivers.value=await admin.value.listDrivers();if(!assignmentForm.value.vehicle_id&&vehicles.value[0])assignmentForm.value.vehicle_id=vehicles.value[0].id;if(!assignmentForm.value.driver_id&&drivers.value[0])assignmentForm.value.driver_id=drivers.value[0].id;}
function clearNotice(){message.value='';error.value='';}
async function run(action,success){clearNotice();busy.value=true;try{await action();await refresh();message.value=success;}catch(e){error.value=String(e?.message||e);}finally{busy.value=false;}}
async function createVehicle(){await run(()=>admin.value.createVehicle(vehicleForm.value),'Vehicle created and acquisition history recorded.');vehicleForm.value={...vehicleForm.value,registration_number:'',make:'',model:'',variant:'',acquisition_odometer:0,acquisition_cost:0};}
async function createDriver(){await run(()=>admin.value.createDriver(driverForm.value),'Driver created.');driverForm.value={name:'',mobile:'',licence_number:'',licence_expiry:''};}
async function assignDriver(){await run(()=>admin.value.assignDriver(assignmentForm.value),'Driver assigned to vehicle.');}
async function showVehicleHistory(vehicle){clearNotice();try{const [events,odo,usage]=await Promise.all([admin.value.listVehicleLifecycleHistory(vehicle.id),admin.value.listOdometerHistory(vehicle.id),admin.value.vehicleUsage(vehicle.id)]);message.value=`${vehicle.registration_number}: ${events.map(e=>e.event_type).join(' → ')} · Odometer ${odo.length} readings · Business ${usage.businessKm} km · Personal ${usage.personalKm} km · Unclassified ${usage.unclassifiedKm} km`;}catch(e){error.value=String(e?.message||e);}}
async function retire(vehicle){const date=prompt('Retirement date (YYYY-MM-DD)',new Date().toISOString().slice(0,10));if(!date)return;const odo=prompt('Retirement odometer',String(vehicle.current_odometer));if(odo==null)return;await run(()=>admin.value.retireVehicle(vehicle.id,{retirement_date:date,retirement_odometer:Number(odo),reason:'Administrative retirement'}),'Vehicle retired.');}
async function sell(vehicle){const date=prompt('Sale date (YYYY-MM-DD)',new Date().toISOString().slice(0,10));if(!date)return;const odo=prompt('Sale odometer',String(vehicle.current_odometer));if(odo==null)return;const amount=prompt('Sale amount', '0');if(amount==null)return;await run(()=>admin.value.sellVehicle(vehicle.id,{sale_date:date,sale_odometer:Number(odo),sale_amount:Number(amount),sale_reference:'ADMIN'}),'Vehicle sold and disposal proceeds recorded.');}
async function transfer(vehicle){const date=prompt('Transfer date (YYYY-MM-DD)',new Date().toISOString().slice(0,10));if(!date)return;const odo=prompt('Transfer odometer',String(vehicle.current_odometer));if(odo==null)return;await run(()=>admin.value.transferVehicle(vehicle.id,{transfer_date:date,transfer_odometer:Number(odo),transfer_amount:0,transfer_reference:'ADMIN'}),'Vehicle transferred.');}
onMounted(refresh);
</script>
<template>
  <section class="kfe-destination" aria-label="Vehicle administration">
    <header><button type="button" @click="emit('back')">‹ More</button><h1>Vehicle & Driver</h1><p>Authoritative administration. Driver operations remain in Work, Performance and Timeline.</p></header>
    <div class="kfe-segmented"><button type="button" :class="{'is-active':tab==='Vehicle'}" @click="tab='Vehicle'">Vehicle</button><button type="button" :class="{'is-active':tab==='Driver'}" @click="tab='Driver'">Driver</button><button type="button" :class="{'is-active':tab==='Assign'}" @click="tab='Assign'">Assignment</button></div>
    <p v-if="message" role="status">{{message}}</p><p v-if="error" role="alert">{{error}}</p>
    <form v-if="tab==='Vehicle'" @submit.prevent="createVehicle">
      <h2>Vehicle</h2><input v-model="vehicleForm.registration_number" required placeholder="Registration number"><input v-model="vehicleForm.make" required placeholder="Make"><input v-model="vehicleForm.model" required placeholder="Model"><input v-model="vehicleForm.variant" placeholder="Variant"><input v-model="vehicleForm.fuel_type" required placeholder="Fuel type"><input v-model="vehicleForm.acquisition_date" required type="date"><select v-model="vehicleForm.acquisition_type"><option>NEW</option><option>USED</option></select><input v-model.number="vehicleForm.acquisition_odometer" required type="number" min="0" placeholder="Acquisition odometer"><input v-model.number="vehicleForm.acquisition_cost" required type="number" min="0" step="0.01" placeholder="Acquisition cost"><button :disabled="busy" type="submit">Add vehicle</button>
    </form>
    <div v-if="tab==='Vehicle'" class="kfe-list"><article v-for="vehicle in vehicles" :key="vehicle.id"><strong>{{vehicle.registration_number}}</strong><span>{{vehicle.make}} {{vehicle.model}} · {{vehicle.lifecycle_status}} · {{vehicle.current_odometer}} km</span><div><button type="button" @click="showVehicleHistory(vehicle)">History</button><button v-if="vehicle.lifecycle_status==='ACTIVE'" type="button" @click="retire(vehicle)">Retire</button><button v-if="['ACTIVE','RETIRED'].includes(vehicle.lifecycle_status)" type="button" @click="sell(vehicle)">Sell</button><button v-if="['ACTIVE','RETIRED'].includes(vehicle.lifecycle_status)" type="button" @click="transfer(vehicle)">Transfer</button></div></article></div>
    <form v-else-if="tab==='Driver'" @submit.prevent="createDriver"><h2>Driver</h2><input v-model="driverForm.name" required placeholder="Name"><input v-model="driverForm.mobile" placeholder="Mobile"><input v-model="driverForm.licence_number" required placeholder="Driving licence number"><input v-model="driverForm.licence_expiry" type="date"><button :disabled="busy" type="submit">Add driver</button><div class="kfe-list"><article v-for="driver in drivers" :key="driver.id"><strong>{{driver.name}}</strong><span>{{driver.licence_number}} · {{driver.status}}</span></article></div></form>
    <form v-else @submit.prevent="assignDriver"><h2>Vehicle assignment</h2><select v-model="assignmentForm.vehicle_id" required><option value="" disabled>Select vehicle</option><option v-for="vehicle in vehicles" :key="vehicle.id" :value="vehicle.id">{{vehicle.registration_number}}</option></select><select v-model="assignmentForm.driver_id" required><option value="" disabled>Select driver</option><option v-for="driver in drivers" :key="driver.id" :value="driver.id">{{driver.name}}</option></select><input v-model="assignmentForm.start_date" required type="date"><input v-model="assignmentForm.reason" placeholder="Reason"><button :disabled="busy" type="submit">Assign driver</button></form>
  </section>
</template>
<style scoped>.kfe-destination{padding:16px}.kfe-destination header{display:grid;gap:6px}.kfe-destination form,.kfe-list{display:grid;gap:10px;margin-top:16px}.kfe-destination input,.kfe-destination select,.kfe-destination button{min-height:44px;padding:10px}.kfe-list article{display:grid;gap:6px;padding:12px;border:1px solid var(--kfe-ui-border);border-radius:12px}.kfe-list article span{opacity:.8}.kfe-list article div{display:flex;gap:8px;flex-wrap:wrap}.kfe-segmented{display:flex;gap:6px;margin-top:12px}.kfe-segmented button.is-active{font-weight:800}</style>
