<script setup>
import { onMounted, ref } from 'vue';
const props=defineProps({application:{type:Object,required:true}});
const open=ref(false),minutes=ref(''),current=ref(0),busy=ref(false),error=ref('');
async function load(){try{const state=await props.application.getWorkScreenState();current.value=Number(state?.shift?.breakMinutes??state?.shift?.break_minutes??0)}catch{current.value=0}}
async function save(){const value=Number(minutes.value);if(!Number.isInteger(value)||value<0){error.value='Break minutes must be a non-negative whole number.';return}const state=await props.application.getWorkScreenState();if(!state?.shift?.active||!state.shift.id){error.value='An active business shift is required.';return}busy.value=true;error.value='';try{await props.application.work.recordBreakMinutes({shiftId:state.shift.id,breakMinutes:value});current.value=value;minutes.value='';open.value=false;window.dispatchEvent(new CustomEvent('kfe:work-state-changed'))}catch(e){error.value=String(e?.message||e)}finally{busy.value=false}}
onMounted(load);
</script>
<template><section class="kfe-break-control" aria-label="Work break handling"><button v-if="!open" type="button" class="kfe-secondary-action" @click="open=true">Break · {{current}} min</button><div v-else class="kfe-break-control__panel"><strong>Break handling</strong><p>Record the total break minutes for the active business shift.</p><label class="kfe-form-label" for="work-break-minutes">Break minutes<input id="work-break-minutes" v-model="minutes" class="kfe-form-input" type="number" min="0" step="1" inputmode="numeric"></label><p v-if="error" class="kfe-error-note" role="alert">{{error}}</p><div class="kfe-admin-actions"><button class="kfe-primary-action" type="button" :disabled="busy" @click="save">Save break</button><button class="kfe-secondary-action" type="button" :disabled="busy" @click="open=false">Cancel</button></div></div></section></template>
<style scoped>.kfe-break-control{display:grid;gap:8px;margin:8px 0}.kfe-break-control__panel{display:grid;gap:10px;padding:14px;border:1px solid var(--kfe-ui-border);border-radius:var(--kfe-ui-radius-lg);background:var(--kfe-ui-surface)}</style>