// KFE 2.0 Vehicle domain: pure business facts and invariants only.
// No UI, browser storage, repository, or application dependencies.

export const VEHICLE_STATUS=Object.freeze({ACTIVE:'ACTIVE',RETIRED:'RETIRED',SOLD:'SOLD',TRANSFERRED:'TRANSFERRED'});
export const VEHICLE_USAGE_SCOPE=Object.freeze({BUSINESS:'BUSINESS',PERSONAL:'PERSONAL',UNCLASSIFIED:'UNCLASSIFIED'});
export const VEHICLE_ODOMETER_SOURCES=Object.freeze({ACQUISITION:10,MAINTENANCE:20,FUEL:30,WORK_SESSION:40,HISTORICAL_CORRECTION:100});
const DAY=/^\d{4}-\d{2}-\d{2}$/;
const text=v=>String(v??'').trim();
const norm=v=>text(v).toUpperCase();
export function assertVehicleDate(value,name='Date'){const valueText=text(value);if(!DAY.test(valueText))throw new RangeError(`${name} must be YYYY-MM-DD`);return valueText;}
export function assertNonNegativeWhole(value,name='Value'){const number=Number(value);if(!Number.isInteger(number)||number<0)throw new RangeError(`${name} must be a whole number`);return number;}
export function assertNonNegativeMoneyPaise(value,name='Amount'){const number=Number(value);if(!Number.isInteger(number)||number<0)throw new RangeError(`${name} must be non-negative paise`);return number;}
export function normalizeRegistration(value){const registration=norm(value);if(!registration)throw new RangeError('Registration Number is required');return registration;}
export function normalizeVehicleInput(input={}){const acquisitionType=norm(input.acquisition_type);if(!['NEW','USED'].includes(acquisitionType))throw new RangeError('Acquisition Type must be New or Used');const registration_number=normalizeRegistration(input.registration_number);const acquisition_date=assertVehicleDate(input.acquisition_date,'Acquisition Date');if(!text(input.make)||!text(input.model))throw new RangeError('Make and Model are required');if(!text(input.fuel_type))throw new RangeError('Fuel Type is required');if(acquisitionType==='USED'&&(input.acquisition_odometer===''||input.acquisition_odometer==null))throw new RangeError('Acquisition Odometer is required for a used vehicle');const acquisition_odometer=assertNonNegativeWhole(input.acquisition_odometer??0,'Acquisition Odometer');return Object.freeze({registration_number,make:text(input.make),model:text(input.model),variant:text(input.variant),fuel_type:text(input.fuel_type),acquisition_date,acquisition_type:acquisitionType,acquisition_odometer,acquisition_cost_paise:assertNonNegativeMoneyPaise(input.acquisition_cost_paise??0,'Acquisition Cost')});}
export function assertUniqueRegistration(rows,registration,ignoreId=null){const value=normalizeRegistration(registration);if(rows.filter(row=>!row.is_deleted).some(row=>row.id!==ignoreId&&norm(row.registration_number)===value))throw new RangeError('Registration Number already exists');return value;}
export function assertOdometerAdvance(previous,current){const prior=assertNonNegativeWhole(previous,'Previous Odometer');const next=assertNonNegativeWhole(current,'Odometer');if(next<prior)throw new RangeError('Odometer cannot move backwards');return next;}
export function assertLifecycleEndpoint(vehicle,{date,odometer},name){const endpointDate=assertVehicleDate(date,`${name} Date`);const endpointOdometer=assertNonNegativeWhole(odometer,`${name} Odometer`);if(endpointDate<vehicle.acquisition_date||endpointOdometer<Number(vehicle.current_odometer??vehicle.acquisition_odometer))throw new RangeError(`${name} endpoint cannot precede the authoritative vehicle state`);if(vehicle.retirement_date&&endpointDate<vehicle.retirement_date)throw new RangeError(`${name} Date cannot precede retirement date`);return Object.freeze({date:endpointDate,odometer:endpointOdometer});}
export function assertVehicleCanRetire(vehicle){if(vehicle.lifecycle_status!==VEHICLE_STATUS.ACTIVE)throw new Error('Only an active vehicle can be retired');}
export function assertVehicleCanSell(vehicle){if(![VEHICLE_STATUS.ACTIVE,VEHICLE_STATUS.RETIRED].includes(vehicle.lifecycle_status))throw new Error('Only an active or retired vehicle can be sold');}
export function assertVehicleCanTransfer(vehicle){if(![VEHICLE_STATUS.ACTIVE,VEHICLE_STATUS.RETIRED].includes(vehicle.lifecycle_status))throw new Error('Only an active or retired vehicle can be transferred');}
export function assertPositiveSaleAmountPaise(value){const amount=assertNonNegativeMoneyPaise(value,'Sale Amount');if(amount<=0)throw new RangeError('Sale Amount must be positive');return amount;}
export function lifecycleEvent(type,date,odometer,amountPaise=0,extra={}){return Object.freeze({event_type:norm(type),effective_date:assertVehicleDate(date,'Lifecycle Event Date'),odometer:assertNonNegativeWhole(odometer,'Lifecycle Event Odometer'),amount_paise:assertNonNegativeMoneyPaise(amountPaise,'Lifecycle Event Amount'),...extra});}
export function vehicleLifetimeKm(vehicle){const endpoint=vehicle?.lifecycle_status===VEHICLE_STATUS.SOLD?vehicle.sale_odometer:vehicle?.lifecycle_status===VEHICLE_STATUS.RETIRED?vehicle.retirement_odometer:vehicle?.lifecycle_status===VEHICLE_STATUS.TRANSFERRED?vehicle.transfer_odometer:vehicle?.current_odometer;if(endpoint==null)return null;return Number(endpoint)-Number(vehicle.acquisition_odometer);}
export function classifyUsageScope(scope){const value=norm(scope);if(value==='BUSINESS')return VEHICLE_USAGE_SCOPE.BUSINESS;if(value==='PERSONAL')return VEHICLE_USAGE_SCOPE.PERSONAL;return VEHICLE_USAGE_SCOPE.UNCLASSIFIED;}
export function usageKmByScope(rows=[]){const totals={businessKm:0,personalKm:0,unclassifiedKm:0};for(const row of rows){const start=Number(row.start_odometer),end=Number(row.end_odometer);if(!Number.isFinite(start)||!Number.isFinite(end)||end<start)continue;const km=end-start;const scope=classifyUsageScope(row.scope);if(scope===VEHICLE_USAGE_SCOPE.BUSINESS)totals.businessKm+=km;else if(scope===VEHICLE_USAGE_SCOPE.PERSONAL)totals.personalKm+=km;else totals.unclassifiedKm+=km;}return Object.freeze(totals);}
export function overlapsAssignment(a,b){return String(a.start_date)<String(b.end_date||'9999-12-31')&&String(b.start_date)<String(a.end_date||'9999-12-31');}
export function assertAssignmentTargets({vehicle,driver,vehicleAssignments=[],driverAssignments=[],startDate,currentAssignment=null}){const start=assertVehicleDate(startDate,'Assignment Start Date');if(!vehicle||vehicle.is_deleted)throw new Error('Vehicle not found');if(!driver||driver.is_deleted)throw new Error('Driver not found');if(vehicle.lifecycle_status!==VEHICLE_STATUS.ACTIVE)throw new Error('Driver cannot be assigned to an inactive or retired vehicle');if(driver.status!=='ACTIVE')throw new Error('Inactive driver cannot receive a new assignment');if(driver.licence_expiry&&driver.licence_expiry<start)throw new Error('Driver licence is expired for the assignment start date');if(vehicleAssignments.filter(a=>a.id!==currentAssignment?.id).some(a=>overlapsAssignment(a,{start_date:start,end_date:null})))throw new Error('Vehicle already has an active assignment');if(driverAssignments.filter(a=>a.id!==currentAssignment?.id).some(a=>overlapsAssignment(a,{start_date:start,end_date:null})))throw new Error('Driver assignment dates overlap');return start;}
export function assertAssignmentEnd(startDate,endDate){const start=assertVehicleDate(startDate,'Assignment Start Date'),end=assertVehicleDate(endDate,'Assignment End Date');if(end<start)throw new RangeError('Assignment End Date cannot be before Start Date');return end;}
