import assert from 'node:assert/strict';
import {describe, it} from 'node:test';
import {createWorkApplication} from '../../js/application/work-application-lifecycle.js';

function fakeRepository(seed){
 const names=['work_days','work_sessions','rides','revenue_records','operational_events','audit','odometer_allocations'];
 const data=Object.fromEntries(names.map(name=>[name,(seed[name]||[]).map(row=>({...row}))]));
 function entity(name){return {async list(){return data[name].map(row=>({...row}));},async get(id){const row=data[name].find(item=>item.id===id);return row?{...row}:null;}};}
 return {entity,async atomic(names,callback){const stores=Object.fromEntries(names.map(name=>[name,{put(row){const index=data[name].findIndex(item=>item.id===row.id);if(index===-1)data[name].push({...row});else data[name][index]={...row};}}]));return callback(stores);},data};
}
const telemetry={recordEvent(){},setActive(){}};
const day=(id,date,status,extra={})=>({id,business_date:date,status,started_at:`${date}T08:00:00.000Z`,ended_at:status==='COMPLETED'?`${date}T17:00:00.000Z`:null,created_at:`${date}T08:00:00.000Z`,updated_at:`${date}T17:00:00.000Z`,...extra});
const shift=(id,date,status,extra={})=>({id,business_date:date,scope:'BUSINESS',status,started_at:`${date}T09:00:00.000Z`,ended_at:status==='COMPLETED'?`${date}T12:00:00.000Z`:null,created_at:`${date}T09:00:00.000Z`,updated_at:`${date}T12:00:00.000Z`,...extra});
const ride=(id,date,extra={})=>({id,business_date:date,scope:'BUSINESS',trip_type:'BUSINESS',status:'OPEN',started_at:`${date}T10:00:00.000Z`,ended_at:null,created_at:`${date}T10:00:00.000Z`,updated_at:null,shift_id:null,...extra});

describe('KFE C4 persisted FSM sanitizer',()=>{
 it('closes open shift and child business trip at completed day boundary',async()=>{const repository=fakeRepository({work_days:[day('d1','2026-09-01','COMPLETED')],work_sessions:[shift('s1','2026-09-01','OPEN')],rides:[ride('r1','2026-09-01',{shift_id:'s1'})]});const app=createWorkApplication({repository,telemetry});await app.currentContext('2026-09-01');assert.equal(repository.data.work_sessions[0].status,'COMPLETED');assert.equal(repository.data.work_sessions[0].ended_at,'2026-09-01T17:00:00.000Z');assert.equal(repository.data.rides[0].status,'COMPLETED');assert.equal(repository.data.rides[0].ended_at,'2026-09-01T17:00:00.000Z');});
 it('keeps a business trip attached to an open shift and open day authoritative',async()=>{const repository=fakeRepository({work_days:[day('d1','2026-09-07','OPEN')],work_sessions:[shift('s1','2026-09-07','OPEN')],rides:[ride('r1','2026-09-07',{shift_id:'s1'})]});const app=createWorkApplication({repository,telemetry});const context=await app.currentContext('2026-09-07');assert.equal(repository.data.rides[0].status,'OPEN');assert.equal(context.trip?.id,'r1');assert.equal(context.trip?.scope,'BUSINESS');assert.equal((await app.state()).state,'BUSINESS_TRIP');});
 it('uses completed parent shift boundary before ride timestamps',async()=>{const repository=fakeRepository({work_days:[day('d1','2026-09-02','OPEN')],work_sessions:[shift('s1','2026-09-02','COMPLETED')],rides:[ride('r1','2026-09-02',{shift_id:'s1',updated_at:'2026-09-02T15:00:00.000Z'})]});const app=createWorkApplication({repository,telemetry});await app.currentContext('2026-09-02');assert.equal(repository.data.rides[0].ended_at,'2026-09-02T12:00:00.000Z');});
 it('falls back to ride.updated_at, then ride.started_at for orphan trips',async()=>{const repository=fakeRepository({work_days:[day('d1','2026-09-03','OPEN')],rides:[ride('r-updated','2026-09-03',{updated_at:'2026-09-03T11:00:00.000Z'}),ride('r-start','2026-09-03',{updated_at:null,started_at:'2026-09-03T10:30:00.000Z'})]});const app=createWorkApplication({repository,telemetry});await app.currentContext('2026-09-03');assert.equal(repository.data.rides.find(row=>row.id==='r-updated').ended_at,'2026-09-03T11:00:00.000Z');assert.equal(repository.data.rides.find(row=>row.id==='r-start').ended_at,'2026-09-03T10:30:00.000Z');});
 it('heals multiple active days, shifts and trips by retaining the newest record',async()=>{const repository=fakeRepository({work_days:[day('old-day','2026-09-04','OPEN'),day('new-day','2026-09-05','OPEN')],work_sessions:[shift('old-shift','2026-09-04','OPEN'),shift('new-shift','2026-09-05','OPEN')],rides:[ride('old-ride','2026-09-04'),ride('new-ride','2026-09-05')]});const app=createWorkApplication({repository,telemetry});await app.currentContext('2026-09-05');assert.equal(repository.data.work_days.find(row=>row.id==='old-day').status,'COMPLETED');assert.equal(repository.data.work_days.find(row=>row.id==='new-day').status,'OPEN');assert.equal(repository.data.work_sessions.find(row=>row.id==='old-shift').status,'COMPLETED');assert.equal(repository.data.work_sessions.find(row=>row.id==='new-shift').status,'OPEN');assert.equal(repository.data.rides.find(row=>row.id==='old-ride').status,'COMPLETED');assert.equal(repository.data.rides.find(row=>row.id==='new-ride').status,'OPEN');});
 it('records sanitizer warnings without changing the FSM audit record contract',async()=>{const repository=fakeRepository({work_days:[day('d1','2026-09-06','COMPLETED')],work_sessions:[shift('s1','2026-09-06','OPEN')],rides:[ride('r1','2026-09-06',{shift_id:'s1'})]});const app=createWorkApplication({repository,telemetry});await app.currentContext('2026-09-06');assert.ok(repository.data.audit.some(row=>row.eventType==='SANITIZE_PERSISTED_CONTEXT'));const fsmAudit=repository.data.audit.find(row=>row.eventType==='SANITIZE_PERSISTED_CONTEXT');assert.ok(fsmAudit.id&&Number.isFinite(fsmAudit.timestamp)&&fsmAudit.entityId);});
});
